<div class="entry-edit">
    <?php echo $this->getFormHtml();?>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('File Mapping') ?></h4>

        <div class="form-buttons"></div>
    </div>
    <div class="fieldset fieldset-wide" id="base_fieldset">
        <div class="hor-scroll">
        <?php echo $this->getMappingHtml(); ?>
        </div>
    </div>
</div>
<style type="text/css">
    #row_mapping label {
        width: 100px;
    }
    #row_mapping .label {
        width: 110px;
    }
    #grid_mapping .scalable {
        width: 100%;
    }
</style>
<?php echo $this->getChildHtml('form_after');?>
