<?php 
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
<div class="container store-switcher clearfix">
    <div class="block-content dropdown">
        <a href="#" class="dropdown-toggle clearfix" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="<?php echo $this->__('Select Store') ?>">
            <?php foreach ($this->getGroups() as $_group): ?>
                <?php if ($_group->getId() == $this->getCurrentGroupId()): ?>
                    <span class="name"><?php echo $this->htmlEscape($_group->getName()) ?></span>
                <?php endif; ?>
            <?php endforeach; ?>
            <span class="icon-dropdown"></span>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($this->getGroups() as $_group): ?>
                <?php if ($_group->getId() != $this->getCurrentGroupId()): ?>
                    <li><a tabindex="-1" href="<?php echo $_group->getHomeUrl() ?>"><?php echo $this->htmlEscape($_group->getName()) ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>            
        </ul>
    </div>
</div>
<?php endif; ?>
