<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$zonda = $this->helper('zonda');
$rowClass = $zonda->getRowClass();
$spanClass = $zonda->getSpanClass();
$b = $zonda->getConfigGroup();

$_productCollection=$this->getLoadedProductCollection();
$_uid = $this->getFrontHash();

$_helper = $this->helper('catalog/output');

//Default image size
$imgWidth = 100;
$imgHeight = 100;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];

$blockName = $this->getBlockName();
$blockDescription = $this->getBlockDescription();
$blockId = $this->getFrontHash();
?>
<div class="">
    <div class="block block-products block-list">
        <?php if ($blockName) : ?>
        <div class="block-title <?php if ($_productCollection->count() > 4) echo 'slider-title'; ?>">
            <strong><span><?php echo $this->__($blockName) ?></span></strong>
        </div>
        <?php endif; ?>
        <div class="block-content">
        <?php if(!$_productCollection->count()): ?>
            <p class="note-msg"><?php echo $this->__('There are no products.') ?></p>
        <?php else: ?>
            <div id="featured-products-list-<?php echo $blockId ?>" class="mini-products-list flexslider flexslider"><ul class="slides">
            <?php 
            $i = 0; 
            foreach ($_productCollection as $_product): ?>
                <?php if ($i % 4 == 0) : ?><li><?php endif; ?>
                <div class="item clearfix">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <img src="<?php echo $zonda->getImage($_product, $imgWidth, $imgHeight, 'thumbnail'); ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <?php echo $this->getReviewsSummaryHtml($_product, true) ?>
                        <?php echo $this->getPriceHtml($_product, true, '-featured-sidebar') ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </div>
                <?php if ($i % 4 == 3) : ?></li><?php endif; ?>
            <?php 
            $i++;
            endforeach; ?>
            <?php if ($i % 4 != 0) : ?></li><?php endif; ?>
            </ul></div>
            <script type="text/javascript">decorateList('featured-products-list-<?php echo $blockId ?>', 'none-recursive')</script>
            <script type="text/javascript">
            //<![CDATA[
                jQuery(function($) {
                    $('#featured-products-list-<?php echo $blockId ?>').flexslider({
                        controlNav: false,
                        animation: 'slide',
                        smoothHeight: true
                    });
                });
            //]]>
            </script>
        <?php endif; ?>
        </div>
    </div>
</div>