<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$zonda = $this->helper('zonda');
$rowClass = $zonda->getRowClass();
$spanClass = $zonda->getSpanClass();
$b = $zonda->getConfigGroup();

$_productCollection=$this->getLoadedProductCollection();
$_uid = $this->getFrontHash();

$_helper = $this->helper('catalog/output');

//Default image size
$imgWidth = 228;
$imgHeight = 228;
//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
$blockName = $this->getBlockName();
$blockDescription = $this->getBlockDescription();
?>
<?php if ($blockName) : ?><h2 class="subtitle"><?php echo $blockName; ?></h2><?php endif; ?>
<?php 
        $_collectionSize = $_productCollection->count();
        //$_columnCount = $this->getColumnCount();
        $i = 0;
        ?>
        <?php if(!$_productCollection->count()): ?>
            <p class="note-msg"><?php echo $this->__('There are no products.') ?></p>
        <?php else: ?>
            <ul id="products_grid_<?php echo $_uid ?>" class="products-grid bx-slider">
            <?php foreach ($_productCollection as $_product): ?>
                <li><div class="item-inner">
                    <?php // Product Image & Price ?>
                    <div class="product-image">
                    <div class="product-image-thumbnail">
			            <?php 
                        if ($b['category']['hover_image'])
                            $hoverImgHtml = $zonda->getHoverImageHtml($_product, $imgWidth, $imgHeight); 
                        ?>            
			            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                            <img<?php if ($hoverImgHtml) echo ' class="primary-image"'; ?> src="<?php echo $zonda->getImage($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                            <?php echo $hoverImgHtml; ?>
			            </a>
                    </div>        

                    <div class="more-info">
                        <a href="<?php echo $zonda->getImage($_product, 400, 400*$b['product']['image_ratio'], 'small_image'); ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="view-product">View Product</a>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="sw-product-quickview">quick view</a>
                    </div>
                    
                    <div class="reviews-wrap">
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                    </div> 
                </div>
                <?php 
                        $labels_tl = ''; $labels_tr = '';
                        if ($b['product']['new_label']) {
                            // New Product 
                            $newsFromDate = $_product->getNewsFromDate();
                            $newsToDate = $_product->getNewsToDate();
                            $new_html= '';
                            if ($newsFromDate && $newsToDate && Mage::app()->getLocale()->IsStoreDateInInterval(Mage::app()->getStore(), $newsFromDate, $newsToDate)){
                                $new_html = '<div class="labels new-pro"></div>';
                                $labels_tr = $new_html;
                            }
                        }
                        if ($b['product']['sale_label']) {
                            // Special Product
//                            
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();
                            $sales_html = '';
                            if ($specialPriceFromDate && $specialPriceToDate && Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $specialPriceFromDate, $specialPriceToDate)) {
                                $specialprice = $_product->getSpecialPrice();
                                $sales_html = '<div class="labels sale-pro"></div>';
                                $labels_tl = $sales_html;
                            }
                        }
                        if ($labels_tl)
                            echo $labels_tl;
                        if ($labels_tr)
                            echo $labels_tr;
                        ?>
                <div class="price-review">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                
                    <div class="actions clearfix">
                        <?php if($_product->isSaleable()): ?>
                            <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else : ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>showOptions('<?php echo $_product->getId()?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                            <?php endif;?>
                        <?php else: ?>
                            <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                        <?php endif; ?>
                        <span class="add-to-links">
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enableothers", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                        </span>
                    </div>
                </div></li>
            <?php $i++; endforeach; ?>
            </ul>
            
            <script type="text/javascript">// <![CDATA[
                var featured_timer_<?php echo $_uid ?>;    
                var products_grid_<?php echo $_uid ?>;
                var winwidth = jQuery(window).outerWidth();
                if (winwidth < 992 && winwidth >= 768){
                    products_grid_<?php echo $_uid ?> = jQuery('#products_grid_<?php echo $_uid ?>.bx-slider').bxSlider({minSlides: 3, maxSlides: 3, slideWidth:235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                }else if(winwidth < 768){
                    products_grid_<?php echo $_uid ?> = jQuery('#products_grid_<?php echo $_uid ?>.bx-slider').bxSlider({minSlides: 1, maxSlides: 1, slideWidth:235, slideMargin: 0, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                }else {
                    products_grid_<?php echo $_uid ?> = jQuery('#products_grid_<?php echo $_uid ?>.bx-slider').bxSlider({minSlides: 4, maxSlides: 4, slideMargin: 21,slideWidth:235 , moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                }
                if (jQuery('#slider-tab').length) {
                    jQuery('.slider-tab-content .tab-pane').hide();
                    jQuery('.slider-tab-content .tab-pane.active').show();   
                }
                jQuery(window).resize(function(e){
                    e.preventDefault();
                    winwidth = jQuery(window).outerWidth();
                    if(featured_timer_<?php echo $_uid ?>) clearTimeout(featured_timer_<?php echo $_uid ?>);
                    featured_timer_<?php echo $_uid ?> = setTimeout(function(){
                        if (winwidth < 992 && winwidth >= 768){
                            products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 2, maxSlides: 2, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                        }else if(winwidth < 768){
                            products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 1, maxSlides: 1, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                        }else {
                            products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 4, maxSlides: 4, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                        }}, 300
                    );
                });
                jQuery(document).ready(function(){
                    var this_time;
                    if (jQuery('#slider-tab').length) {
                        jQuery('#slider-tab li').click(function(){
                            if(this_time) clearTimeout(this_time);
                            this_time = setTimeout(function(){
                                jQuery('.slider-tab-content .tab-pane').show();
                                if (winwidth < 992 && winwidth >= 768){
                                    products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 2, maxSlides: 2, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                                }else if(winwidth < 768){
                                    products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 1, maxSlides: 1, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                                }else {
                                    products_grid_<?php echo $_uid ?>.reloadSlider({minSlides: 4, maxSlides: 4, slideWidth: 235, slideMargin: 21, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
                                }
                                jQuery('.slider-tab-content .tab-pane').hide();
                                jQuery('.slider-tab-content .tab-pane.active').show();
                            }, 200);
                            
                        });
                    }
                });
                
            // ]]></script>
            
            <?php endif; ?>