<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar clearfix">
<?php 
            $_helper = $this->helper('catalog/product_compare');
        ?>
    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="sorter-holder clearfix">
        
        <div class="sort-by">
            <?php if(Mage::app()->getFrontController()->getRequest()->getModuleName() != 'blog'):  ?>
            <a class="button btn-compare" onclick="setLocation('<?php echo $_helper->getListUrl(); ?>')"><span><span><?php echo $this->__('Compare'); ?></span></span></a>
            <?php endif; ?>
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>" class="sort-direction"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
            <?php else: ?>
                <a href="<?php  echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>" class="sort-direction"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php  endif; ?>
        </div>

        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <div class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <div title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $this->__('View as') ?>&nbsp;<?php echo $_label ?></div>
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $this->__('View as') ?>&nbsp;<?php echo $_label ?></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
    <div class="pager">
        <div class="limiter">
            <a class="button btn-compare" onclick="setLocation('<?php echo $_helper->getListUrl(); ?>')"><span><span><?php echo $this->__('Compare'); ?></span></span></a>
            <div class="show-by">
                <label><?php echo $this->__('Show: ') ?></label>
                <select onchange="setLocation(this.value)">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
        </div>
        <?php echo $this->getPagerHtml() ?>
        
    </div>
</div>
<?php endif; ?>
