<?php
/** @var Affirm_Affirm_Block_Payment_Form $this **/
?>
<style type="text/css">
    .affirm-module-version {
        display: none;
    }

    .affirm_payment_info1 {
        color: #034082;
        font-size: 14px;
    }
    .affirm_payment_info2 {
        color: #6f6f6f;
        font-size: 12px;
        line-height: normal;
    }
    .affirm_payment_info2 ul {
        margin: 10px 0;
    }
    .affirm_payment_info2 ul li {
        list-style-type: disc;
        padding-left: 8px;
        margin-left: 16px;
    }
</style>
<ul class="form-list affirm" id="payment_form_affirm" style="display:none;">
    <li class="form-alt">
        <div class="affirm_payment_info1"><?php echo $this->__('How does Affirm work?'); ?></div>
            <div class="affirm_payment_info2">
                <ul>
                <li><?php echo $this->__('Just enter some basic personal information and get a real-time credit decision.'); ?></li>
                <li><?php echo $this->__("You will complete your application on the Affirm website."); ?></li>
                <li><?php echo $this->__("If you're approved and confirm a loan, your purchase will be on its way as soon as it's ready."); ?></li>
                </ul>
            </div>
    </li>
</ul>
<span class="affirm-module-version"><?php echo $this->helper('affirm')->getModuleConfigVersion(); ?></span>
