/* System Config Styles */
/* Created at <?php echo date("Y-m-d H:i:s") ?> */
<?php 
$zonda = Mage::helper('zonda');
$slider = Mage::helper('eternal_homeslider');
$b = $zonda->getConfigGroup(Mage::registry('zonda_css_generate_store'));
$c = $zonda->getConfigGroupDesign(Mage::registry('zonda_css_generate_store'));
$brands = Mage::helper('eternal_brands');
$bg_mode = $c['general']['body_bg_mode'];
$bg_image = $zonda->getBackgroundImageUrl();
$bg_texture = $zonda->getTextureUrl();
$header_texture = $zonda->getHeaderTextureUrl();
$footer_texture = $zonda->getFooterTextureUrl();
$footer_top_texture = $zonda->getFooterTopTextureUrl();
$twitter_icon = $zonda->getTwitterIcon();
$header_minicart_texture = $zonda->getMinicartTextureUrl();
?>

/*========== Common Styles ==========*/
body {
    background-color: <?php echo $c['general']['body_bg_color'] ?>;
    <?php if (($bg_mode == 'image') && $bg_image) :?>
        background: url(<?php echo $bg_image ?>) repeat center center;
    <?php elseif (($bg_mode == 'texture') && $bg_texture) : ?>
        background: url(<?php echo $bg_texture ?>) repeat center center;
    <?php endif; ?>
    <?php if ($c['general']['body_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['general']['body_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['general']['body_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['general']['body_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['general']['body_font_family_group'] ?>;
    <?php endif; ?>
    color: <?php echo $c['general']['font_color'] ?>;
}
h1,
h2,
h3,
h4,
h5,
h6,
.page-title h1, 
.page-title h2 {
    <?php if ($c['general']['title_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['general']['title_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['general']['title_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['general']['title_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['general']['title_font_family_group'] ?>;
    <?php endif; ?>
    color: <?php echo $c['general']['title_color'] ?>;
}
a {
    color: <?php echo $c['general']['link_color'] ?>;
}
a:hover {
    color: <?php echo $c['general']['link_hover_color'] ?>;
}
.button,
.sbToggle,
.pager .pages ol li a,
.pager .pages ol li.current,
.button-normal {
    display: inline-block;
    background-color: <?php echo $c['general']['button_bg_color'] ?>;
    <?php if ($c['general']['button_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['general']['button_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['general']['button_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['general']['button_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['general']['button_font_family_group'] ?>;
    <?php endif; ?>
    color: <?php echo $c['general']['button_font_color'] ?>;
    font-size: <?php echo $c['general']['button_font_size'] ?>;
    text-transform: uppercase;
}
.cms-no-route .main-content .form-search .input-text {
    border: solid 1px <?php echo $c['general']['button_bg_color'] ?>;
}
.pager .pages ol li a {
    color: #ffffff;
}
.button:hover,
.sbToggle:hover,
.sbToggle:focus,
.pager .pages ol li a:hover,
.pager .pages ol li a:focus ,
.button-normal:hover,
.btn-remove2:hover,
.btn-remove:hover
{
    background-color: <?php echo $c['general']['button_hover_bg_color'] ?>;
    color: <?php echo $c['general']['button_hover_font_color'] ?>;
}
.button.link-wishlist:hover,
.button.link-wishlist:focus,
.button.link-compare:hover,
.button.link-compare:focus {
    background-color: <?php echo $c['general']['button_bg_color'] ?>;
}
<?php if ($c['product']['addcart_customize']): ?>
    .btn-cart {
        color: <?php echo $c['product']['addcart_color'] ?>;
        background-color: <?php echo $c['product']['addcart_bg_color'] ?>;
    }
    .btn-cart:hover {
        color: <?php echo $c['product']['addcart_hover_color'] ?>;
        background-color: <?php echo $c['product']['addcart_hbg_color'] ?>;
    }
<?php endif; ?>
<?php if ($c['product']['addto_customize']): ?>
    .button.link-wishlist,
    .button.link-compare {
        background-color: <?php echo $c['product']['addto_bg_color'] ?>;
    }
    .button.link-wishlist:hover,
    .button.link-compare:hover {
        background-color: <?php echo $c['product']['addto_hbg_color'] ?>;
    }
<?php endif; ?>
.pager .pages ol li a:hover,
.pager .pages ol li a:focus {
    color: #ffffff;
}
input.input-text, 
select, 
textarea,
.sbSelector,
.sbOptions {
    background: <?php echo $c['general']['input_bg_color'] ?>;
    border: solid 1px <?php echo  $c['general']['input_border_color'] ?>;
    color: <?php echo $c['general']['input_text_color'] ?>;
}
/* Grouped fields */
.form-list label,
.product-view .box-tags .form-add label {
    <?php if ($c['general']['label_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['general']['label_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['general']['label_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['general']['label_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['general']['label_font_family_group'] ?>;
    <?php endif; ?>
    font-size: 14px;
    text-transform: capitalize;
    color: <?php echo $c['general']['label_color'] ?>;    
}
.form-list label.required em,
.content label.required em {
    color: <?php echo $c['general']['required_color'] ?>;
}
/*========== Header Top ==========*/

/*========== Header ==========*/
.header-container {    
    <?php if ($header_texture): ?>background-image: url(<?php echo $header_texture ?>);
    <?php else: ?>
    background-color: <?php echo $c['header']['header_bg_color'] ?>;
    <?php endif; ?>
    background-position: center center;
    background-repeat: repeat;    
}
.header-container a,
.block-minicart, 
.block-language, 
.block-currency,
.block-minicart .mini-cart-button,
.store-switcher .block-content a,
#mini-cart .mini-cart-button .price,
.block.block-minicart .block-subtitle,
.header-top .block-minicart .mini-cart-button.button,
#nav li a{
    color: <?php echo $c['header']['header_font_color'] ?>;
    <?php if ($c['header']['header_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['header']['header_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['header']['header_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['header']['header_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['header']['header_font_family_group'] ?>;
    <?php endif; ?>
}
.header-container .block-language a .item-value,  
.header-container .block-currency a .item-value {
    color: <?php echo $c['header']['cl_font_color'] ?>;
}
.menu-active #menu-button a{
    background-color: <?php echo $c['top_menu']['mobile_icon_hover_bg_color'] ?>;
    color: <?php echo $c['top_menu']['mobile_icon_hover_font_color'] ?>;
}
.menu-active #menu-button .btn-navbar .icon-bar{
    background-color: <?php echo $c['top_menu']['mobile_icon_hover_font_color'] ?>;
}
.header-container.fixed .header-menu-back {
    background-color: <?php echo $c['header']['sticky_header_bg_color'] ?>;
}
<?php if($b['header']['header_type'] == 'type1'):?>
.header-container .logo{
    height: 120px;
    width: 190px;
    line-height: 120px;
    text-align: center !important;
    background-color: <?php echo $b['header']['logo_bgcolor'] ?>;
}
.header-container.fixed .header-menu-container {
   max-width: 1030px;
   padding: 0 15px;
}
.header-container.fixed .sticky-logo{
    height: 70px;
    line-height: 70px;
    text-align: center !important;
    background-color: <?php echo $b['header']['logo_bgcolor'] ?>;
}
.header-top{
    border-bottom: solid 1px rgba(0,0,0,0.2);    
}
.header-menu{
    border-top: solid 1px rgba(255,255,255,0.1);    
}
.header-container.fixed .header-menu{
    border: none;
}
.header-right,
.header-container.fixed .header-menu {
    width: 750px;    
    float: right;
}
#custommenu-mobile #menu-button{
    margin: 0;
    line-height: 32px;
    padding-top: 23px;
    padding-bottom: 24px;
    position: relative;
    left: -10px;
}
#custommenu-mobile #menu-button a,
#custommenu-mobile #menu-button a:link,
#custommenu-mobile #menu-button a:visited{
    display: block;
    height: 32px;
    padding-top: 10px;
}
<?php else: ?>
.header-container .logo{
    height: 90px;
    line-height: 90px;
    position: relative;
    bottom: 2px;
    left: -6px;
    width: <?php echo $b['header']['logo_bg_width'] ?> !important;
    text-align: center !important;
}
#custommenu-mobile #menu-button a,
#custommenu-mobile #menu-button a:link,
#custommenu-mobile #menu-button a:visited {
    padding: 29px 20px;
}
.header-container.fixed .logo{
    display: block !important;
    bottom: 4px;
}
.header-container .header-menu-right{
    background-image: url('../images/header_bg.png');
    background-repeat: no-repeat;
    background-position: 50% -12px;
}
.header-container.fixed .header-menu-right{
    background: none;
}
.header-menu-right .header-right{
    float: right;    
}
.header-menu-right .header-right .nav-container{
    float: right;
}
.store-switcher .block-content {
    left: -10px;
}
#custommenu-mobile #menu-button{
    margin-left: 83px;
}
.quick-access {
    position: relative;
}
<?php endif; ?>
/*========== Top Links ==========*/
.toplinks a:hover{    
    color: <?php echo $c['header']['header_hover_font_color']?>;
}
.toplinks li{
    color: <?php echo $c['header']['header_font_color'] ?>;
}
/*========== Currency, Language Selector, Store Switcher ==========*/
.dropdown-menu > li > a:hover,
.dropdown-menu > li > a:focus,
.dropdown-menu > .active > a,
.dropdown-menu > .active > a:hover,
.dropdown-menu > .active > a:focus,
.dropdown-submenu:hover > a {
    background-color: <?php echo $c['header']['cl_link_hover_bg_color'] ?> !important;
    background-image: none;    
}
.block-currency .block-content > a, 
.block-language .block-content > a,
.store-switcher .block-content > a {
    
}
.dropdown-menu > li{
    border-top: solid <?php echo $c['header']['cl_dd_top_border_width'] .' '.$c['header']['cl_dd_top_border_color'] ?>;
}
.open>a{        
    background-color: <?php echo $c['header']['cl_link_hover_bg_color'] ?>;
}
/*========== Minicart ==========*/
#mini-cart .mini-cart-button,
#mini-cart .dropdown-menu {
    <?php if ($c['header']['header_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['header']['header_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['header']['header_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['header']['header_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['header']['header_font_family_group'] ?>;
    <?php endif; ?>    
}
#mini-cart.open .mini-cart-button,
#mini-cart.open .mini-cart-button .price{
    background-color: <?php echo $c['header']['mc_link_hover_bg_color'] ?>;
    color: <?php echo $c['header']['mc_link_hover_font_color'] ?>;    
}
#mini-cart .dropdown-menu{
    background-color: <?php echo $c['header']['mc_dropdown_bg_color'] ?>;
    <?php if ($header_minicart_texture): ?>background-image: url(<?php echo $header_minicart_texture ?>);<?php endif; ?>
    background-position: center center;
    background-repeat: repeat;
    border: solid <?php echo $c['header']['mc_dropdown_border_width'] .' '. $c['header']['mc_dropdown_border_color']?>;
    color: <?php echo $c['header']['mc_dropdown_font_color'] ?>;    
}
/*========== Search Form ==========*/
.header-container .header-container .form-search .input-text,
.header-container .form-search .button{    
    background-color: <?php echo $c['header']['search_textbox_bg_color']?>;  
}
.header-container .form-search .button span.icon-search,
.header-container .form-search .button span.icon-close{
    display: block;
    width: 100%;
    height: 30px;
    margin-top: 0;
}
.header-container .form-search .button span.icon-search{
    background: url(../images/icons/<?php echo $c['header']['search_btn_icon_type'] ?>icon_search.png) no-repeat center center;    
}
.header-container .form-search .button:hover span.icon-search,
.header-container .form-search .button:focus span.icon-search{
    background-image: url(../images/icons/<?php echo $c['header']['search_btn_hover_icon_type'] ?>icon_search.png);
    margin-top: 0;
}
.header-container .form-search .button span.icon-close{
    background: url(../images/icons/<?php echo $c['header']['search_btn_icon_type'] ?>icon_search_close.png) no-repeat center center;
}
.header-container .form-search .input-text{
    color: <?php echo $c['header']['search_text_color'] ?>;
}
<?php if ($b['header']['header_type'] == 'type1'): ?>
.header-container .form-search {
    border: solid <?php echo $c['header']['search_text_border_width'].' '.$c['header']['search_text_border_color'] ?>;    
}
<?php else: ?>
.header-container .form-search {
    background: url(../images/border_line.png) repeat-y 0 50%;
}
.header-container .form-search .button {
    background: url(../images/border_line.png) repeat-y 100% 50%;
    width: 57px;
    height: 31px;    
}
.header-container .form-search .input-text {
    padding-left: 20px;
    font-style: italic;    
}
<?php endif; ?>
/*========== Main Menu ==========*/
.header-menu {
    <?php if ($menu_texture): ?>background-image: url(<?php echo $menu_texture ?>);<?php endif; ?>
    background-position: center center;
    background-repeat: repeat;    
    position: relative;
}
#menu-button a {
    background-color: transparent;
}
div.menu{
    <?php if($b['header']['header_type'] == 'type1'):?>
        margin: 0 24px 0 0;
    <?php else: ?>
        margin: 0 ;
    <?php endif; ?>
}
div.menu a,
#nav li a,
#blog_nav li a,
#nav-links a{
    font-size: <?php echo $c['top_menu']['nav_top_font_size']?>;
    <?php if ($c['top_menu']['nav_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['top_menu']['nav_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['top_menu']['nav_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['top_menu']['nav_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['top_menu']['nav_font_family_group'] ?>;
    <?php endif; ?>
    <?php if ($b['header']['header_type'] == 'type2'): ?>
        background: url(../images/border_line.png) repeat-y 0 50%;
        padding: 0 20px;
    <?php else: ?>
        padding: 0 12px;
    <?php endif; ?>
}
<?php if ($b['header']['header_type'] == 'type1'): ?>
div.menu a:hover,
div.menu a:focus,
div.menu.active a,
#nav>li>a:hover,
#nav>li>a:focus,
#nav>li.active>a,
#nav>li.over>a,
#nav-links li a:hover,
#nav-links li a:focus,
#nav-links li.active a,
#nav-links li.over a,
#blog_nav>li>a:hover,
#blog_nav>li>a:focus,
#blog_nav>li.active>a,
#blog_nav>li.over>a
{
    color: <?php echo $c['top_menu']['link_hover_color'] ?>;
    background-color: <?php echo $c['top_menu']['link_bg_hover_color'] ?>;
    background-image: none;
}
#custommenu{    
        left: -12px;        
}
.header-container.fixed .header-menu-container .parentMenu{
    padding: 19px 0;
}
#nav ul, #nav div, #blog_nav ul {
    top: 79px;
}
<?php else: ?>
div.menu a:hover,
div.menu a:focus,
div.menu:hover a,
div.menu.active a,
#nav li:hover a,
#nav li a:hover,
#nav li a:focus,
#nav li.active a,
#nav li.over a,
#blog_nav li:hover a,
#blog_nav li a:hover,
#blog_nav li a:focus,
#blog_nav li.active a,
#blog_nav li.over a,
#nav-links li a:hover,
#nav-links li a:focus,
#nav-links li.active a,
#nav-links li.over a {
    background: none;
}
#custommenu .menu:hover,
#custommenu .menu.active,
#nav li.level0:hover,
#nav li.level0.over,
#blog_nav li.level0:hover,
#blog_nav li.level0.over{
    background-color: <?php echo $c['top_menu']['link_bg_hover_color'] ?>;
}
div.menu:hover a,
div.menu.active a {
     color: <?php echo $c['top_menu']['link_hover_color'] ?>;
}
html[xmlns] #menu-button, 
html[xmlns] .parentMenu,
#nav li.level0,
#blog_nav li.level0 {
    line-height: 28px;
    padding-top: 22px;
    padding-bottom: 26px;
}
div.eternal-custom-menu-popup{
    padding-top: 14px !important;
}
#nav ul, #nav div, #blog_nav ul {
    top: 76px;
}
<?php endif; ?>
.menu-mobile .parentMenu:hover{
    background-color: <?php echo $c['top_menu']['popup_hover_bg_color']?>;
}
#nav ul li,
#blog_nav ul li,
div.itemSubMenu a {
    <?php if ($c['top_menu']['popup_border_bottom']): ?>
        border-bottom: <?php echo $c['top_menu']['popup_border_bottom_style'] ?> 1px <?php echo $c['top_menu']['popup_border_bottom_color'] ?> ;
    <?php else: ?>
        border: none;
    <?php endif; ?>
}
#nav ul.level0 li a,
#blog_nav ul.level0 li a {
    background: none;
}
div.eternal-custom-menu-popup>div,
#custommenu-mobile #menu-content,
#nav ul,
#nav div,
#blog_nav ul,
#blog_nav div,
#nav-links ul,
#nav-links div {
    border-style: solid;    
    border-width: <?php echo $c['top_menu']['popup_border_width'] ?>;
    border-color: <?php echo $c['top_menu']['popup_border_color'] ?>;    
    background-color: <?php echo $c['top_menu']['popup_bg_color'] ?>;
    background-clip: padding-box;
}
div.eternal-custom-menu-popup a,
.menu-mobile a{
    <?php if ($c['top_menu']['popup_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['top_menu']['popup_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['top_menu']['popup_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['top_menu']['popup_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['top_menu']['popup_font_family_group'] ?>;
    <?php endif; ?>
}
div.eternal-custom-menu-popup a.level1,
.menu-mobile a.level1,
.menu-mobile .parentMenu a ,
#nav ul li.level1 a,
#blog_nav ul li.level1 a{
    font-size: <?php echo $c['top_menu']['popup_level1_font_size'] ?>;
    color: <?php echo $c['top_menu']['popup_level1_font_color'] ?>;   
}
div.eternal-custom-menu-popup a.level2,
.menu-mobile a.level2,
#nav ul li.level2 a,
div.eternal-custom-menu-popup a.level3,
.menu-mobile a.level3,
#nav ul li.level3 a,
div.eternal-custom-menu-popup a.level4,
.menu-mobile a.level4,
#nav ul li.level4 a,
div.eternal-custom-menu-popup a.level5,
.menu-mobile a.level5,
#nav ul li.level5 a,
#blog_nav ul li.level2 a{
    font-size: <?php echo $c['top_menu']['popup_level2_font_size'] ?>;
    color: <?php echo $c['top_menu']['popup_level2_font_color'] ?>;
}
.menu-mobile.level0 > .parentMenu > a:hover,
div.eternal-custom-menu-popup a.level1:hover,
.menu-mobile a.level1:hover,
div.eternal-custom-menu-popup a.level2:hover,
.menu-mobile a.level2:hover{
    color: <?php echo $c['top_menu']['popup_hover_color'] ?>;
}
#menu-button .btn-navbar .icon-bar {
    background-color: <?php echo $c['top_menu']['mobile_icon_bar_color'] ?>;
}
<?php if ($b['gmap']['gmap_enable']): ?>
.contacts-index-index .header-container {
    position: absolute;
    z-index: 100;
}
<?php endif; ?>

/*========== Arrow Buttons ==========*/
.flex-direction-nav a,
.bx-has-controls-direction .bx-controls-direction a,
.footer-tweets .twitter-nav-container a{
    background-color: <?php echo $c['general']['arrow_bg_color'] ?>;
}
.flex-direction-nav a:hover,
.flex-direction-nav a:focus,
.bx-has-controls-direction .bx-controls-direction a:hover,
.bx-has-controls-direction .bx-controls-direction a:focus,
.footer-tweets .twitter-nav-container a:hover{
    background-color: <?php echo $c['general']['arrow_hover_bg_color'] ?>;
}
/*========== Home Slider ==========*/
<?php if($slider->getConfig('general/enabled', Mage::registry('zonda_css_generate_store')) && $slider->getConfig('general/slider_type', Mage::registry('zonda_css_generate_store')) == 'background'): ?>
    .cms-index-index .main-container .main-banner,
    .cms-index-index .main-container .main,
    .cms-index-index .footer-container{
        display: none;
    }
<?php endif; ?>
/*========== Brand Slider ==========*/
<?php if ($brands->getConfig('slider/custom_enable', Mage::registry('zonda_css_generate_store'))&&  $b['footer']['show_two_lows']) : ?>
    .footer-banner {
        background-color: <?php echo $c['footer']['banner_bg_color'] ?>;        
        background-position: center center;
        background-repeat: repeat;
    }
    .brand-slider-wrap {
        padding: 0;
        float: right;
        width: 786px;
    }
    .custom-block-title{ 
        float: left;
        background: url('../images/brand-logo.png') no-repeat;
        width: 214px;
        height: 125px;
    }
    .footer #brand-slider ul.slides li {
        background: url(../images/banner_border_line_right.png) repeat-y 0 50%;
    }
    .footer #brand-slider ul.slides a {
        background: url(../images/banner_border_line_left.png) repeat-y 100% 50%;
    }
    #brand-slider .bx-controls a {
    position: absolute;
        top: -47px;
    }
    #brand-slider .bx-controls a.bx-next{
        right: 0;
    }
    #brand-slider .bx-controls a.bx-prev{
        right: 27px;
    }
    .footer-banner {
        margin-top: 20px;
    }
    .brand-slider-wrap {
        padding: 20px 0;
    }
    #brand-slider .flex-direction-nav i {
        vertical-align: top;
        margin-top: 4px;
    }
    #brand-slider a:hover,
    #brand-slider a:hover {
        padding: 0;
    }
    <?php 
    if ($b['footer']['show_two_lows']): 
        $shadow_bottom = $c['footer']['top_bg_color'];  
    else:
        $shadow_bottom = $c['footer']['bg_color'];
    endif; ?> 
    .banner-shadow {
        background: <?php echo $c['footer']['banner_bg_color'] ?>; 
        background: -moz-linear-gradient(top, <?php echo $c['footer']['banner_bg_color'] ?> 0%, <?php echo $shadow_bottom ?> 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,<?php echo $c['footer']['banner_bg_color'] ?>), color-stop(100%, <?php echo $shadow_bottom ?>)); 
        background: -webkit-linear-gradient(top, <?php echo $c['footer']['banner_bg_color'] ?> 0%, <?php echo $shadow_bottom ?> 100%);
        background: -o-linear-gradient(top, <?php echo $c['footer']['banner_bg_color'] ?> 0%, <?php echo $shadow_bottom ?> 100%); 
        background: -ms-linear-gradient(top, <?php echo $c['footer']['banner_bg_color'] ?> 0%, <?php echo $shadow_bottom ?> 100%);
        background: linear-gradient(to bottom, <?php echo $c['footer']['banner_bg_color'] ?> 0%, <?php echo $shadow_bottom ?> 100%); 
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='<?php echo $c['footer']['banner_bg_color'] ?>', endColorstr='<?php echo $shadow_bottom ?>',GradientType=0 );
    }
    <?php if ($b['footer']['show_two_lows']):?>    
    .footer-top .footer-column-1 h3.custom-title {
        background: url('../images/brand-logo.png');
        width: 214px;
        height: 125px;
        margin-top: -91px;
        padding-top: 15px;
        padding-right: 9px;
        text-align: center;
        color: #c4c4c4;
        margin-bottom: 17px;
    }
    <?php endif; ?>
<?php else :?>
    #brand-slider .bx-controls a {
        position: absolute;
    top: 11px;
    }
    #brand-slider .bx-controls a.bx-prev{
        left: -45px;
    }
    #brand-slider .bx-controls a.bx-next{
        right: -45px;
    }
    .brand-slider-wrap{
        padding: 75px 45px;
    }
<?php endif; ?>
/*========== Footer ==========*/
.footer {
    color: <?php echo $c['footer']['color'] ?>;
    background-color: <?php echo $c['footer']['bg_color'] ?>;
    <?php if ($footer_texture): ?>background-image: url(<?php echo $footer_texture ?>);<?php endif; ?>
    background-position: center center;
    background-repeat: repeat;
    font-size: <?php echo $c['footer']['font_size'] ?>;
    font-weight: <?php echo $c['footer']['font_weight'] ?>;
<?php if ($c['footer']['font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['footer']['font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['footer']['font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['footer']['font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['footer']['font_family_group'] ?>;
<?php endif; ?>
}
.footer-tweets {
    background-color: <?php echo $c['twitter']['bg_color'] ?>;
    color: <?php echo $c['twitter']['text_color'] ?>;
}
.footer-tweets a {
    color: <?php echo $c['twitter']['link_color'] ?>;
}
.footer-tweets a:hover {
    color: <?php echo $c['twitter']['hover_color'] ?>;
}
.footer-tweets .date {
    color: <?php echo $c['twitter']['date_color'] ?>;
}
.footer-tweets .twitter-icon {
    background-image: url(<?php echo $twitter_icon ?>);
}
.footer-tweets .text,
.footer-tweets .Twitter-Title {
    font-size: <?php echo $c['twitter']['font_size'] ?>;
}
.footer-top{
    color: <?php echo $c['footer']['top_color'] ?>;
    background-color: <?php echo $c['footer']['top_bg_color'] ?>;
    <?php if ($footer_top_texture): ?>background-image: url(<?php echo $footer_top_texture ?>);<?php endif; ?>
    background-position: center center;
    background-repeat: repeat;
    font-size: <?php echo $c['footer']['font_size'] ?>;
    font-weight: <?php echo $c['footer']['font_weight'] ?>;
<?php if ($c['footer']['font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['footer']['font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['footer']['font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['footer']['font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['footer']['font_family_group'] ?>;
<?php endif; ?>
}
.footer h3,
.footer .title {
    color: <?php echo $c['footer']['title_color'] ?>;
    font-size: <?php echo $c['footer']['title_font_size'] ?>;
    font-weight: <?php echo $c['footer']['title_font_weight'] ?>;
<?php if ($c['footer']['title_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['footer']['title_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['footer']['title_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['footer']['title_font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['footer']['title_font_family_group'] ?>;
<?php endif; ?>
}
.footer-top h3,
.footer-top .title {
    color: <?php echo $c['footer']['top_color'] ?>;
}
.footer-top a,
.footer-main a {    
    transition: color 300ms ease-in-out, padding 300ms ease-in-out;
       -moz-transition: color 300ms ease-in-out, padding 300ms ease-in-out;
    -webkit-transition: color 300ms ease-in-out, padding 300ms ease-in-out;
         -o-transition: color 300ms ease-in-out, padding 300ms ease-in-out;
}
.footer-top a{
    color: <?php echo $c['footer']['top_color'] ?>;
}
#twitter-footer-slider,
#twitter-footer-slider .date{
    font-size: <?php echo $c['footer']['font_size'] ?>;
}
.footer-main a {
    color: <?php echo $c['footer']['color'] ?>;
}
.footer-main a:hover,
.footer-main a:focus {
    color: <?php echo $c['footer']['hover_color'] ?>;
    padding-left: 5px;    
}
.footer-top a:hover,
.footer-top a:focus {
    color: <?php echo $c['footer']['top_hover_color'] ?>;
    padding-left: 5px;    
}
.footer-top .fblike-box a:hover,
.footer-top .fblike-box a:focus,
.footer-main .fblike-box a:hover,
.footer-main .fblike-box a:focus {
    padding-left: 0;
}
.footer-top #twitter-footer-slider a,
.footer-main .fblike-box .facebook-like-wrap a {
    color: <?php echo $c['footer']['top_hover_color'] ?>;
}
.footer-main #twitter-footer-slider a,
.footer-main .fblike-box .facebook-like-wrap a {
    color: <?php echo $c['footer']['hover_color'] ?>;
}
.footer address{
    font-size: <?php echo $c['footer']['bottom_font_size'] ?>;
    font-weight: <?php echo $c['footer']['bottom_font_weight'] ?>;
    <?php if ($c['footer']['bottom_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['footer']['bottom_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['footer']['bottom_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['footer']['bottom_font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['footer']['bottom_font_family_group'] ?>;
<?php endif; ?>
}
.footer .footer-bottom address{
    color: <?php echo $c['footer']['bottom_text_color'] ?>;
}
/*========== Quick Access, Wishlist, Compare Links ==========*/
/*========== Main ==========*/
/*========== Breadcrumbs ==========*/
.breadcrumbs {
    color: <?php echo $c['breadcrumbs']['text_color'] ?>;
    <?php if ($c['breadcrumbs']['bcs_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['breadcrumbs']['bcs_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['breadcrumbs']['bcs_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['breadcrumbs']['bcs_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['breadcrumbs']['bcs_font_family_group'] ?>;
    <?php endif; ?>
    font-size: <?php echo $c['breadcrumbs']['text_size'] ?>;
    font-weight: normal;
}
.breadcrumbs a {
    color: <?php echo $c['breadcrumbs']['text_color'] ?>;
}

/*========== Product ==========*/
.products-grid .item-inner,
.products-list .item-inner,
.product-essential-inner .product-img-box,
.cc-item-container {
    background: <?php echo $c['product']['bg_color'] ?>;
    border: solid 1px <?php echo $c['product']['border_color'] ?>;
}
.products-grid .ratings {
    background: <?php echo $c['product']['bg_color'] ?>;
}
.product-name a,
.products-grid .product-name a,
.products-list .product-name a,
.price-box .minimal-price-link,
.price-box .price-from .price-label,
.price-box .price-to .price-label,
.product-view .product-name,
.product-view .product-name h1,
.review-row .review-title,
.product-view .box-up-sell h1.subtitle,
.product-view .block-related h1.subtitle,
.col-sidebar .block-content ul li .product-name a,
.on_date,
.cc-product-name a,
.product-tabs-content li .cc-product-name a,
.product-view .box-tags h3,
#fancybox-content .product-essential .product-shop .std{
    color: <?php echo $c['product']['name_font_color'] ?>;
    <?php if ($c['product']['name_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['name_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['name_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['name_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['name_font_family_group'] ?>;
    <?php endif; ?>
}
.price {
    color: <?php echo $c['product']['price_color'] ?>;
    <?php if ($c['product']['price_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['price_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['price_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['price_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['price_font_family_group'] ?>;
    <?php endif; ?>
}
.price-box .old-price .price {
    color: <?php echo $c['product']['price_old_color'] ?>;
}
.labels .sales,
.labels .new {
    color: <?php echo $c['product']['labels_color'] ?>;
    <?php if ($c['product']['labels_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['labels_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['labels_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['labels_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['labels_font_family_group'] ?>;
    <?php endif; ?>
    font-size: 14px;
}
.ratings .amount a {
    color: <?php echo $c['product']['review_color'] ?>;
    <?php if ($c['product']['review_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['review_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['review_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['review_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['review_font_family_group'] ?>;
    <?php endif; ?>
}
.desc,
.desc .disc li,
.product-tabs-content,
.product-tabs-content h2,
.product-tabs-content li,
.product-tabs-content li a,
.quickview-main .product-view .short-description
 {
    color: <?php echo $c['product']['description_color'] ?>;
    <?php if ($c['product']['description_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['description_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['description_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['description_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['description_font_family_group'] ?>;
    <?php endif; ?> 
    font-size: 13px;
    line-height: 1.6;
}
.product-view .info-container p,
.product-view .info-container p.alert-urls a,
.product-view .info-container .product-pricing,
#fancybox-content .product-essential p,
.product-options dt,
.product-options dd,
.availability,
.quickview-main .product-shop .product-pricing{
    <?php if ($c['product']['labels_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['labels_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['labels_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['labels_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['labels_font_family_group'] ?>;
    <?php endif; ?>
    color: <?php echo $c['product']['font_color'] ?>;
}
.product-options-bottom,
.product-options {
    border-top: solid 1px <?php echo $c['product']['border_color'] ?>;
}
.product-view .product-options .options .sbSelector {
    background: transparent;
    border: solid 1px <?php echo $c['product']['border_color'] ?>;
}
.under-lines {
    border-top: solid 1px <?php echo $c['product']['border_color'] ?>;
    border-bottom: solid 1px <?php echo $c['product']['border_color'] ?>;
}
/*========== quickview ==========*/ 
<?php if(Mage::getStoreConfig('quickview/general/enableview')): ?>
.for-responsive {
    display: none;
}
<?php else: ?>
.more-info,
.for-more{
    display: none;
}
.for-responsive {
    display: block;
}
<?php endif; ?>

/*========== Tab ==========*/
.by_name {
    color: <?php echo $c['tabs']['colored_border_color'] ?>;
}
<?php if($c['tabs']['tab_type'] == 'tab'): ?>
    .product-tabs-ul,
    .product-tabs-ul li{
        background-color: <?php echo $c['tabs']['tab_bg_color'] ?>;        
    }
    .product-tabs-ul li.active {
        background-color: <?php echo $c['tabs']['tab_selector_bg_color'] ?>;
    }
    .product-tabs-ul li a {
        <?php if ($c['tabs']['tab_font_family_group'] == 'google') : ?>
            font-family: "<?php echo $c['tabs']['tab_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
        <?php elseif ($c['tabs']['tab_font_family_group'] == 'custom') : ?>
            font-family: <?php echo $c['tabs']['tab_font_family_custom'] ?>;
        <?php else : ?>
            font-family: <?php echo $c['tabs']['tab_font_family_group'] ?>;
        <?php endif; ?>
        color: <?php echo $c['tabs']['tab_font_color'] ?>;
        font-size: 12px;    
    }
    .product-tabs-ul li.active a {
        color: <?php echo $c['tabs']['tab_selector_font_color'] ?>;
    }
    .cc-item-container {
        border: solid 1px <?php echo $c['tabs']['border_color'] ?>;
    }
    <?php if ($c['tabs']['tab_position'] == 'top') :?>
        .data-con {
            height: 238px;
        }
        <?php if($c['tabs']['use_border']):?>
            .product-tabs-ul {
                border-left: solid 1px <?php echo $c['tabs']['border_color'] ?>;
                border-bottom: solid 1px <?php echo $c['tabs']['border_color'] ?>;
                padding-top: 2px;
            }
            .product-tabs-ul li,
            .product-view .data-content {
                border: solid 1px <?php echo $c['tabs']['border_color'] ?>;
            } 
            .product-tabs-ul li {
                border-left: none;
                margin-top: -2px;
                margin-bottom: -1px;
            }
            .product-view .data-content {
                border-top: none;
                background-color: <?php echo $c['tabs']['content_bg_color'] ?>;
                padding-left: 20px;
            }
            .product-tabs-ul li.active {
                border-bottom: none;
                border-top: solid <?php echo $c['tabs']['colored_border_width'] . ' ' . $c['tabs']['colored_border_color'] ?>;
                margin-top: -1px;
                margin-bottom: -2px; 
            }
            
        <?php else : ?>
            <?php if($c['tabs']['use_colored_border']):?>
                .product-tabs-ul {
                    border-bottom: solid <?php echo $c['tabs']['colored_border_width'] . ' ' . $c['tabs']['colored_border_color'] ?>;
                }
            <?php endif; ?>
        <?php endif; ?>
    <?php else: ?>
        #product-tabs {
            border: solid 1px <?php echo $c['tabs']['border_color'] ?>;
            position: relative;
            margin: 0;
            padding: 0;
            background-color: <?php echo $c['tabs']['tab_bg_color'] ?>;
        }
        #product-tabs > dt {
            width: 230px;
            border-bottom: solid 1px <?php echo $c['tabs']['border_color'] ?>;
            line-height: 55px;
            height: 55px;
            cursor: pointer;
            padding: 0 25px;
            text-transform: uppercase;
            background-color: <?php echo $c['tabs']['tab_bg_color'] ?>;
            <?php if ($c['tabs']['tab_font_family_group'] == 'google') : ?>
                font-family: "<?php echo $c['tabs']['tab_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
            <?php elseif ($c['tabs']['tab_font_family_group'] == 'custom') : ?>
                font-family: <?php echo $c['tabs']['tab_font_family_custom'] ?>;
            <?php else : ?>
                font-family: <?php echo $c['tabs']['tab_font_family_group'] ?>;
            <?php endif; ?>
            color: <?php echo $c['tabs']['tab_font_color'] ?>;
            font-size: 12px; 
        }
        #product-tabs > dt.open {
            width: 232px;
            position: relative;
            z-index: 10;
            background-color: <?php echo $c['tabs']['tab_selector_bg_color'] ?>;
            color: <?php echo $c['tabs']['tab_selector_font_color'] ?>;
            border-left: solid <?php echo $c['tabs']['colored_border_width'] . ' ' . $c['tabs']['colored_border_color'] ?>;
            margin-left: -1px;
        }
        #product-tabs > dd {
            position: absolute;
            right: 0;
            top: 0;
            left: 230px;
            border-left: solid 1px <?php echo $c['tabs']['border_color'] ?>;
            border-bottom-width: 0;
            padding: 37px 33px 37px 33px;
            background-color: <?php echo $c['tabs']['content_bg_color'] ?>;
        }        
    <?php endif; ?>

<?php elseif($c['tabs']['tab_type'] == 'accordion'): ?>
<?php endif; ?>
/*========== Compare Products Page ==========*/
.data-table tr,
.data-table tr.even,
.checkout-cart-index .shipping-form,
.content {
    background-color: <?php echo $c['product']['body_bg_color'] ?>;        
}
.checkout-cart-index .shipping-form,
.data-table,
.content {
    border-bottom: 2px solid <?php echo $c['block']['border_color'] ?>;
}
.heading,
.checkout-cart-index .data-table thead tr {
    background-color: <?php echo $c['product']['header_bg_color'] ?>;
}
.checkout-cart-index .cart-table th {
    border-bottom: solid 3px <?php echo $c['general']['body_bg_color'] ?>;
}
.heading,
.data-table th,
.data-table td {
    border-color: <?php echo $c['general']['body_bg_color'] ?>;
}
.heading,
.data-table th {
    <?php if ($c['product']['labels_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['product']['labels_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['product']['labels_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['product']['labels_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['product']['labels_font_family_group'] ?>;
    <?php endif; ?>
}
/*========== Category ==========*/
.category-banner .category-title,
.category-banner .category-title h1 {
    <?php if ($c['category']['banner_title_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['category']['banner_title_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['category']['banner_title_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['category']['banner_title_font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['category']['banner_title_font_family_group'] ?>;
<?php endif; ?>
    font-weight: bold !important;
    font-size: <?php echo $c['category']['banner_title_size'] ?>;
    color: <?php echo $c['category']['banner_title_color']?>;
}
.category-banner .category-description {
    <?php if ($c['category']['banner_description_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['category']['banner_description_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
<?php elseif ($c['category']['banner_description_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['category']['banner_description_font_family_custom'] ?>;
<?php else : ?>
    font-family: <?php echo $c['category']['banner_description_font_family_group'] ?>;
<?php endif; ?>
    font-weight: normal;
    font-size: <?php echo $c['category']['banner_description_size'] ?>;
    color: <?php echo $c['category']['banner_description_color']?>;
}
/*========== Toolbar ===========*/
.toolbar,
.pager {
    background-color: <?php echo $c['category']['toolbar_bg_color'] ?>;
    font-size: <?php echo $c['category']['toolbar_font_size'] ?>;
    <?php if ($c['category']['toolbar_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['category']['toolbar_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['category']['toolbar_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['category']['toolbar_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['category']['toolbar_font_family_group'] ?>;
    <?php endif; ?>
    text-transform: uppercase;
    color: <?php echo $c['category']['toolbar_font_color'] ?>;
}
/*========== Sidebar, Block, Data Table ==========*/
.block .block-title {
    background-color: <?php echo  $c['block']['block_title_bg_color'] ?>;
    border-bottom: solid 2px <?php echo $c['block']['border_color'] ?>;
}
.block .block-title strong {
    display: block;
    font-size: <?php echo $c['block']['block_title_font_size']?>;
    font-weight: <?php echo $c['block']['block_title_font_weight'] ?>;
    text-transform: <?php echo $c['block']['block_title_text_transform'] ?>;
    color: <?php echo $c['block']['block_title_font_color'] ?>;
    <?php if ($c['block']['block_title_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['block']['block_title_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['block']['block_title_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['block']['block_title_font_family_custom'] ?>;
    <?php else : ?>
    font-family: <?php echo $c['block']['block_title_font_family_group'] ?>;
    <?php endif; ?>
}
.akordeon-border-bottom,
.block-layered-nav .block-content .actions{
    border-bottom: 2px solid <?php echo $c['general']['body_bg_color'] ?>;
}
.col-sidebar .block-content {
    border-bottom: 2px solid <?php echo $c['block']['border_color'] ?>;
}
.col-sidebar .block-bestseller .block-content  ul.products-grid li {
    border-top: solid 5px <?php echo $c['general']['body_bg_color'] ?>;
}
.akordeon-heading,
.filter-item-head,
.block .block-subtitle{
    <?php if ($c['block']['category_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['block']['category_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['block']['category_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['block']['category_font_family_custom'] ?>;
    <?php else : ?>
    font-family: <?php echo $c['block']['category_font_family_group'] ?>;
    <?php endif; ?>
    font-size: <?php echo $c['block']['category_font_size']?>;
    color: <?php echo $c['block']['category_font_color'] ?>;
    font-weight: <?php echo $c['block']['category_font_weight'] ?>;
    text-transform: <?php echo $c['block']['category_text_transform'] ?>;
}
.akordeon-heading a,
.filter-item-body .price p,
.filter-item-body .price .text-box,
.filter-item-body .price input[type="text"]
{
    color: <?php echo $c['block']['category_font_color'] ?>;
}
.col-sidebar .block .block-content {
    background-color: <?php echo $c['block']['bg_color'] ?>;
}
.block .akordeon ul li a, 
.block .akordeon ol li a,
.filter-item .filter-item-body ol li,
.filter-item .filter-item-body ul li,
.filter-item .filter-item-body ol li a,
.filter-item .filter-item-body ul li a,
.col-sidebar .block-content ul li a,
.currently .label,
.currently .value{
    <?php if ($c['block']['sub_category_font_family_group'] == 'google') : ?>
    font-family: "<?php echo $c['block']['sub_category_font_family'] ?>", "Helvetica Neue", Helvetica, Arial, sans-serif;
    <?php elseif ($c['block']['sub_category_font_family_group'] == 'custom') : ?>
    font-family: <?php echo $c['block']['sub_category_font_family_custom'] ?>;
    <?php else : ?>
    font-family: <?php echo $c['block']['sub_category_font_family_group'] ?>;
    <?php endif; ?>
    font-size: <?php echo $c['block']['sub_category_font_size']?>;
    color: <?php echo $c['block']['sub_category_font_color'] ?>;
    font-weight: <?php echo $c['block']['sub_category_font_weight'] ?>;
    text-transform: <?php echo $c['block']['sub_category_text_transform'] ?>;
}
.filter-item-body .price .text-box input[type="text"] {
    border: solid 1px <?php echo $c['block']['border_color'] ?>;
    background-color: transparent;
}
.block .akordeon ul li a:hover,
.akordeon-heading a:hover,
.filter-item .filter-item-body ol li a:hover,
.filter-item .filter-item-body ul li a:hover,
.col-sidebar .block-content ul li a:hover{
    color: <?php echo $c['general']['link_hover_color'] ?>;    
}
/*========== Checkout Page ==========*/
/*========== Form List ==========*/
/*========== My Account ==========*/
/*========== Home Page Slider ==========*/
/*========== Slider Controls, Background Colors ==========*/
#slider-tab {
    border-bottom: solid 1px <?php echo $c['general']['input_border_color'] ?>;
}
#slider-tab>li>a {
    <?php if ($c['general']['label_font_family_group'] == 'google') : ?>
        font-family: "<?php echo $c['general']['label_font_family'] ?>", Arial, "Helvetica Neue", Helvetica,  sans-serif;
    <?php elseif ($c['general']['label_font_family_group'] == 'custom') : ?>
        font-family: <?php echo $c['general']['label_font_family_custom'] ?>;
    <?php else : ?>
        font-family: <?php echo $c['general']['label_font_family_group'] ?>;
    <?php endif; ?>
}
#slider-tab>.active>a {
    border: solid 1px <?php echo $c['general']['input_border_color'] ?>;
    border-bottom-color: <?php echo $c['general']['body_bg_color']?>;
}
/*========== Responsive ==========*/
<?php if ($b['header']['header_type'] == 'type1') :
    $body_width = '1030px';
    else:
    $body_width = '1262px';
    endif;
?>
<?php if ($zonda->isResponsive()): ?>
    @media(max-width: 991px){
        <?php if ($b['header']['header_type'] == 'type1') :?>            
            .header-right{
                max-width: 497px;
            }
            .toplinks a{
                margin-left: 8px;
            }
            .block-currency{
                margin-left: 5px;
            }
            .cart-value{
                display: none;
            }
            .block-minicart .block-content{
                padding: 4px 0;
            }
            #custommenu-mobile #menu-button{
                margin: 0;
                line-height: 32px;
                padding-top: 23px;
                padding-bottom: 24px;
                position: relative;
                left: -10px;
            }
            #menu-button a,
            #menu-button a:link,
            #menu-button a:visited{
                display: block;
                height: 32px;
                padding-top: 10px;
            }
        <?php else: ?>
            .header-container .logo{
                left: 0;
            }
            .block-currency{
                margin-left: 5px;
            }                          
            #menu-button a,
            #menu-button a:link,
            #menu-button a:visited{
                padding: 29px 20px;
            }            
            #menu-content{
                margin-top: 26px;
            } 
            .block-switcher,
            .store-switcher .block-content {
                left: 0 !important;
            }
        <?php endif; ?>       
        
        <?php if ($brands->getConfig('slider/custom_enable', Mage::registry('zonda_css_generate_store'))): ?>
            .brand-slider-wrap {
                width: 515px;
            }            
        <?php endif; ?>
    }
    @media(max-width: 767px){
        <?php if(!($slider->getConfig('general/enabled') && $slider->getConfig('general/slider_type') == 'background')): ?>
            .header-container {
            position: relative !important;
        }
        <?php endif;?>
        <?php if ($b['header']['header_type'] == 'type1') :?>
            .header-container .container{
                padding: 0 !important;
            }
            .header-container .container.store-switcher {
                padding: 0 20px !important;
            }
            .header-right{
                max-width: none;
                width: 100%;
            }
            .header-right .header-top .left{
                float: none !important;
            }
            .header-top,
            .header-menu{
                border: none;
            } 
            .header-menu{
                padding-left: 20px;
                margin-top: 5px;
            }           
            #custommenu-mobile #menu-button{
                padding: 0;
                left: 0;
            }
            #menu-button a, 
            #menu-button a:link, 
            #menu-button a:visited{
                height: 40px;
                margin-top: 3px;
            }
            .mobile-block-container{
                padding: 0 20px;
            }
            .header-container .form-search {
                background: url(../images/border_line.png) repeat-y 0 50%;
                border: none;
            }
            .header-container .form-search .button{
                width: 57px;
            }
            .quick-access{
                margin-top: 3px;
            }
        <?php else: ?>
            .header-container .header-menu-right{
                background-position: 10px -12px;
            }            
        <?php endif; ?>
            .header-menu-right .header-right.menu-active,
            .menu-active .mobile-bg{
                background-color: <?php echo $c['top_menu']['mobile_icon_hover_bg_color'] ?>; 
            }
            <?php if ($brands->getConfig('slider/custom_enable', Mage::registry('zonda_css_generate_store'))): ?>
            .brand-slider-wrap {
                width: 100%;
                float: none;
            }
            #brand-slider {
                padding: 0 30px;
            }
            .footer-top .footer-column-1 h3.custom-title {
                width: auto;
                height: auto;
                background: none;
                margin-top: 50px;
                text-align: left;
                padding: 0;
        color: <?php echo $c['footer']['top_color'] ?>;
        margin-bottom: 11px;
            }
            #brand-slider .left-border-cover,
            #brand-slider .right-border-cover {
                display: block;
                position: absolute;
                width: 1px;
                top: 0;
                bottom: 0;
                background-color: #929292;
                z-index: 1000;
            }
            #brand-slider .left-border-cover{
                left: 30px;
            }
            #brand-slider .right-border-cover {
                right: 30px;
            }
            #brand-slider .bx-controls a {
                top: 15px;
                background-color: transparent;
            }
            #brand-slider .bx-controls a.bx-prev{
                left: 0;
            }
            #brand-slider .bx-controls a.bx-next{
                right: 0;
            }
        <?php endif; ?>
        .data-table.cart-table tbody tr {
            border-bottom: solid 2px <?php echo $c['general']['body_bg_color'] ?>;
        }
    }    
<?php else: ?>
@media(min-width: <?php echo $body_width?>){
    body{
    width: <?php echo $body_width?>;
    }
    .container{
        max-width: none !important;
        width: 1030px;
    }
    .header-container .logo{
        width: 190px;
    }
    .header-container .header-right{            
        margin-left: 60px;
        width: 750px;
    }
}
<?php endif; ?>
