<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
$c = $zonda->getConfigGroupDesign();
$rowClass = $zonda->getRowClass();
$spanClass = $zonda->getSpanClass();

$_helper = $this->helper('catalog/output');
?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<script>
    var _affirm_config = {
        public_api_key: "X2171C522CC0K1RR", /* Use the PUBLIC API KEY Affirm sent you. */
        script: "//cdn1-sandbox.affirm.com/js/v2/affirm.js"
    };
    (function(l,g,m,e,a,f,b){var d,c=l[m]||{},h=document.createElement(f),n=document.getElementsByTagName(f)[0],k=function(a,b,c){return function(){a[b]._.push([c,arguments])}};c[e]=k(c,e,"set");d=c[e];c[a]={};c[a]._=[];d._=[];c[a][b]=k(c,a,b);a=0;for(b="set add save post open empty reset on off trigger ready setProduct".split(" ");a<b.length;a++)d[b[a]]=k(c,e,b[a]);a=0;for(b=["get","token","url","items"];a<b.length;a++)d[b[a]]=function(){};h.async=!0;h.src=g[f];n.parentNode.insertBefore(h,n);delete g[f];d(g);l[m]=c})(window,_affirm_config,"affirm","checkout","ui","script","ready");
    affirm.ui.ready( function() { updateAffirmAsLowAs( <?php echo str_replace(array('.', '$'), '', Mage::helper('core')->currency($_product->getFinalPrice(),true,false)); ?>  ) } ); // change to your template value for product or cart price
    function updateAffirmAsLowAs( amount ){
        if ( ( amount == null ) || ( amount > 1700000 ) || (amount < 14900) ) { return; } // Only display as low as for items over $10 CHANGE the 1000 FOR A DIFFERENT LOWER LIMIT. amount > 1700000 represents the Affirm UPPER limit of 17k
        // payment estimate options
        var options = {
            apr: "0.10", // percentage assumed APR for loan
            months: 12, // can be 3, 6, or 12
            amount: amount // USD cents
        };
        try {
            typeof affirm.ui.payments.get_estimate; /* try and access the function */
        }
        catch (e) {
            return; /* stops this function from going any further - affirm functions are not loaded and will throw an error */
        }
        // use the payment estimate response
        function handleEstimateResponse (payment_estimate) {
            // the payment comes back in USD cents
            var dollars = ( ( payment_estimate.payment + 99 ) / 100 ) | 0; // get dollars, round up, and convert to int
            // Set affirm payment text
            var a = document.getElementById('affirm-learn-more');
            var iText = ('innerHTML' in a)? 'innerHTML' : 'textContent';
            a[iText] = "Try now with <img src='<?php echo Mage::getBaseUrl('media') ?>/content/affirm-logo.jpg' class='affirm-logo'> for as low as $" + dollars + " a month. <span>Learn More</span>";
            // open the customized Affirm learn more modal
            a.onclick = payment_estimate.open_modal;
            a.style.visibility = "visible";
        };
        // request a payment estimate
        affirm.ui.payments.get_estimate(options, handleEstimateResponse);
    }
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential row">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <?php echo $this->getChildHtml('grouped_submit') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
        <div class="product-essential-inner col12">
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
                <?php // show price and new, save sales in media.phtml
                //echo $this->getPriceHtml($_product) ?>
                <div class="add-links-wrap clearfix">
                    <?php if ($zonda->getConfig('product/addthis_enable')) : ?>
                        <!-- Social bookmarks from http://www.addthis.com/get/sharing  -->
                        <div class="addthis-icons clearfix">
                            <span><?php echo $this->__('Share:') ?> </span>
                            <div class="addthis_toolbox addthis_default_style addthis_16x16_style">
                            <a class="addthis_button_preferred_1"></a>
                            <a class="addthis_button_preferred_2"></a>
                            <a class="addthis_button_preferred_3"></a>
                            <a class="addthis_button_preferred_4"></a>
                            <a class="addthis_button_compact"></a>
                            <a class="addthis_counter addthis_bubble_style"></a>
                            </div>
                            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5054e6c6502d114f"></script>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="product-shop">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <div class="price-review">
                    <?php echo $this->getPriceHtml($_product) ?>
                    <div class="price-review-wrap">
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <a href="#customer-reviews" class="highlight-link review-toggle" id="write-review-link"><?php echo $this->__('Write a Review') ?></a>
                    </div>
                </div>
                <div class="info-container">
                    <?php if($_product->getId() == 7 || $_product->getId() == 33 || $_product->getId() == 35 || $_product->getId() == 49): ?>
                        <a class="riskfree" href="<?php echo $this->getUrl('riskfree'); ?>"><img src="<?php echo $this->getSkinUrl('images/riskfree.png'); ?>"/></a>
                    <?php endif; ?>
                    <?php /* if ($this->canEmailToFriend()): ?>
                        <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="link-friend" title="<?php echo $this->__('Email to a Friend') ?>"><?php echo $this->__('Email To a Friend') ?></a></p>
                    <?php endif; */ ?>
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php if($_product->getId() == 7 || $_product->getId() == 33 || $_product->getId() == 35 || $_product->getId() == 49): ?>
                        <p class="warranty"><?php echo $this->__('Comes With 1 Year Warranty') ?></p>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getChildHtml('product_brand') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>
                    <?php if($_product->getId() == 33): ?>
                        <a href="<?php echo $this->getUrl('refurbished-faqs'); ?>" class="highlight-link"><?php echo $this->__('Click here to learn more about our refurbished products.') ?></a></p>
                    <?php endif; ?>
                    <?php if($_product->getId() == 35): ?>
                        <a href="<?php echo $this->getUrl('limited-time-offer'); ?>" class="highlight-link"><?php echo $this->__('Click here for special limited time offer.') ?></a></p>
                    <?php endif; ?>
                    <?php if($_product->getId() == 49): ?>
                        <a href="<?php echo $this->getUrl('limited-time-offer'); ?>" class="highlight-link"><?php echo $this->__('Click here for special limited time offer.') ?></a></p>
                    <?php endif; ?>
                </div>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <div class="product-options-bottom">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('partialoptions') ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                            <?php /* <div class="add-links-wrap clearfix">
                                <?php echo $this->getChildHtml('addto') ?>
                            </div> */ ?>
                        </div>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <div class="product-options-bottom">
                            <div class="add-links-wrap clearfix">
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    </div>
                <?php endif;?>
                </form>

                <a id="affirm-learn-more" style="visibility: none" href="#"></a>

                <?php if($_product->isSaleable()): ?>
                    <!--
                    <div id="subscription-wrapper">
                        <form action="<?php echo $this->getUrl('gcheckout/subscription/confirm') ?>" method="post" id="special_product_subscription">

                            <div id="subscription-message">

                                <div class="page-title">
                                    <div class='product_image'></div>
                                    <div class="information-title">
                                        <h1>Beautiful skin and terrific savings - what's not to love?</h1>
                                        <p>Join the Replenish & Save Program and you'll get a 20% discount on automatic refills of your favorite JeNu products!</p>
                                    </div>
                                    <div class="close-bottom" onclick="hideModal();">
                                    </div>
                                </div>
                                <div class="title-separator"></div>
                                <div class="notify-text">

                                    <h1>Yes! Please enroll me in the Replenish & Save program</h1>
				<span>It's easy! Every two months from the date of your first order (which we are shipping immediately), we will auto-ship the treatments you
select below and give you a 20% discount. Checking the box(es) means you agree to have your credit card charged every two months
when the Replenish & Save Program product(s) ship. But no worries, you can cancel your membership in the program at any time by
calling JeNu Customer Service at 866-565-JENU.
				</span>
                                </div>
                                <div class="box-new-product">
                                    <?php
                                    $active_offers = Mage::getStoreConfig('jenumodal/settings/offers');
                                    $active_offers = str_replace(' ', '', $active_offers);
                                    $offers = explode(',', $active_offers);
                                    ?>
                                    <?php foreach($offers as $n=>$offer): ?>
                                        <div class="add-new-product">
                                        <?php if (isset($elements)) : ?>
                                            <?php if (is_array($elements)) : ?>
                                                <?php if (!in_array($offer, $elements) && !empty($offer)) : ?>
                                                    <?php $special_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $offer) ?>
                                                    <?php if (is_object($special_product)) : ?>
                                                        <input type="checkbox" class="checkbox" alt="<?php echo $special_product->getName() ?>" id="<?php echo $special_product->getId() ?>">
                                                        <div class="productname-area">
                                                            <a href="<?php echo $special_product->getProductUrl() ?>" >
                                                                <?php echo $special_product->getName() ?>
                                                            </a>
                                                            <span> - <?php echo Mage::helper('core')->formatPrice($special_product->getAwSarpSubscriptionPrice(), false); ?></span>
                                                            <span class="lower-interests">- <?php echo 100 - number_format(($special_product->getAwSarpSubscriptionPrice()/$special_product->getPrice()) * 100, 0) ?>% savings</span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        </div>
                                        <script>
                                            jQuery(".sub-image.<?php echo $offer ?>").mouseover(function(){
                                                jQuery("#toll-tips-pdp.<?php echo $offer ?>").show();
                                            });
                                            jQuery(".sub-image.<?php echo $offer ?>").mouseout(function(){
                                                jQuery("#toll-tips-pdp.<?php echo $offer ?>").hide();
                                            });
                                        </script>

                                    <?php endforeach; ?>
                                </div>
                                <div class="buttons-confirmation">
                                    <div class="button-spec" id="spec-sending" onclick="checkSubscription();">
				<span>
					<span id="continueButton"><?php echo $this->__('Continue to Cart') ?></span>
				</span>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </form>
                    </div>
                    -->
                <?php endif; ?>

                <?php if (($c['tabs']['tab_type'] == 'accordion') || (($c['tabs']['tab_type'] == 'tab') && ($c['tabs']['tab_position'] == 'top'))): ?>
                <div class="product-collateral">
                    <div class="product-info">
                        <div class="product-tabs">
                            <div class="box-additional box-tabs">
                                <?php
                                $info_tabs_html = trim($this->getChildHtml('info_tabs'));
                                if ($info_tabs_html)
                                    echo $info_tabs_html;
                                ?>
                            </div>
                        </div>
                        <script type="text/javascript">
                        //<![CDATA[
                        jQuery(function($){
                            <?php // open review tab ?>
                            $("#goto-reviews").click(function() {
                               tabs.remoteTabs('product_tabs_tabreviews');
                            });
                        });
                        //]]>
                        </script>
                    </div>
                </div>
                <?php endif; ?>
                <?php if($_product->getId() == 7 || $_product->getId() == 33 || $_product->getId() == 35 || $_product->getId() == 49): ?>
                    <?php
                        $obj = Mage::getModel('catalog/product');
                        $_extraproduct = $obj->load(30); // Enter your Product Id in $product_id
                    ?>
                    <div class="alsobought">
                        <h3><?php echo $this->__('Customers Also Bought') ?></h3>
                        <div class="prod-image">
                            <a href="<?php echo $_extraproduct->getProductUrl();?>"><img src="<?php echo $_extraproduct->getImageUrl();?>"/></a>
                        </div>
                        <div class="prod-info-right">
                            <div class="prodname">
                                <a href="<?php echo $_extraproduct->getProductUrl();?>" class="highlight-link"><?php echo $_extraproduct->getName();?></a>
                            </div>
                            <?php echo $this->getReviewsSummaryHtml($_extraproduct, 'short') ?>
                            <script>
                                jQuery('.prod-info-right .goto-reviews').attr('href','<?php echo $_extraproduct->getProductUrl();?>#customer-reviews');
                            </script>
                            <div class="price-box">
                                <span class="regular-price">
                                    <span class="price"><?php echo Mage::helper('core')->formatPrice($_extraproduct->getPrice(), false); ?></span>
                                </span>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>

    <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct')): ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    if (url.indexOf('wishlist') > 0) {
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                    } else {
                        url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                        var data = jQuery('#product_addtocart_form').serialize();
                        data += '&isAjax=1';
                        jQuery('#loading-mask').show();
                        try {
                            jQuery.ajax({
                                url : url,
                                dataType : 'json',
                                type : 'post',
                                data : data,
                                success : function(data) {
                                    jQuery('#loading-mask').hide();
                                    if(data.status == 'ERROR'){
                                        alert(data.message);
                                    }else{
                                        if(jQuery('.block-minicart .block-content')){
                                            jQuery('.block-minicart .block-content').replaceWith(data.minicart);
                                            jQuery('[data-hover="dropdown"]').dropdownHover();
                                        }
                                        jQuery('#after-loading-success-message').show();
                                    }
                                }
                            });
                        } catch (e) {
                        }
                    }

                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
        <?php else : ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
        <?php endif; ?>
    </div>

    <div class="product-essential-reviews row">
        <div class="product-essential-inner col12">

            <?php if($_product->getId() == 7 || $_product->getId() == 33 || $_product->getId() == 35 || $_product->getId() == 49): ?>
                <div class="gallerywrap">
                    <div class="videogallery">
                        <h3><?php echo $this->__('Video Gallery') ?></h3>
                        <div class="clearfix"></div>
                        <ul class="vidslides vidgallery">
                            <li class="vid"><h4><?php echo $this->__('Why The Gel Matters') ?></h4>
                                <a class="vidlink fancybox.iframe" href="//www.youtube.com/embed/pt72Fa87xQM?autoplay=1"><img src="<?php echo $this->getSkinUrl('images/thumb-whythegelmatters.jpg'); ?>"/></a></li>
                            <li class="vid"><h4><?php echo $this->__('How to Use Video') ?></h4>
                                <a class="vidlink fancybox.iframe" href="//www.youtube.com/embed/EhuI4vGZbvw?autoplay=1"><img src="<?php echo $this->getSkinUrl('images/thumb-howtouse.jpg'); ?>"/></a></li>

                        </ul>
                    </div>
                    <div class="bagallery">
                        <h3><?php echo $this->__('Before & After Gallery') ?></h3>
                        <h4><?php echo $this->__('Independent Study Photos') ?></h4>
                        <div class="baslideswrap">
                            <ul class="baslides ba-set-prod">
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-jacobsen.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-savin.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-cotran.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-peddemors1.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-peddemors2.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-mont.jpg'; ?>" alt="Before And After" /></li>
                                <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'content/ba/ba-is-sheraton.jpg'; ?>" alt="Before And After" /></li>
                            </ul>
                        </div>
                        <script type="text/javascript">
                            //<![CDATA[
                            jQuery(document).ready(function(){
                                jQuery('.ba-set-prod').slick({
                                    adaptiveHeight: true
                                });
                                jQuery('.vidgallery').slick({
                                    adaptiveHeight: true,
                                    slidesToShow: 2
                                });
                                jQuery(".vidlink").fancybox({
                                    maxWidth	: 640,
                                    maxHeight	: 360,
                                    fitToView	: true,
                                    width		: '640',
                                    height		: '360',
                                    autoSize	: true,
                                    aspectRatio: true,
                                    closeClick	: true,
                                    openEffect	: 'none',
                                    closeEffect	: 'none'
                                });
                            });
                            //]]>
                        </script>
                    </div>
                </div>
            <?php endif; ?>
            <?php $reviewcount = $_product->getRatingSummary()->getReviewsCount(); ?>
            <?php if ($reviewcount > 0):?>
                <div class="reviews-summary-wrap">
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?><div class="btn-writereview"><input type="button" class="button button-normal review-toggle" value="Write Your Review"></div>
                </div>
                <div class="line-separator1"></div>
            <?php endif; ?>
            <div class="reviews-bottomwrap">
                <?php echo $this->getChildHtml('product_customer_reviews') ?>
                <?php echo $this->getChildHtml('review_form') ?>
            </div>

        </div>

    </div><!--product-essential-reviews-->

    <?php if (($c['tabs']['tab_type'] == 'tab') && ($c['tabs']['tab_position'] == 'left')) : ?>
        <div class="product-collateral">
                    <div class="product-info">
                        <div class="col12 product-tabs">
                            <div class="box-additional box-tabs">
                                <?php
                                $info_tabs_html = trim($this->getChildHtml('info_tabs'));
                                if ($info_tabs_html)
                                    echo $info_tabs_html;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                //<![CDATA[
                jQuery("#goto-reviews, #goto-reviews-form").click(function() {
                    jQuery("#product-tabs #tab-tabreviews").click();
                });
                //]]>
            </script>
    <?php endif; ?>
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('catalog.product.related')?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>