<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */ 
?>                                                               
<?php if($this->getCurrencyCount()>1): ?>
<?php
// store currency code eg. USD, INR
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();

// store currency symbol eg. $ 
$currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();

// store currency name eg. Indian Rupee
$currency_name = Mage::app()->getLocale()->currency( $currency_code )->getName();
?>
<div class="block block-currency">
    <div class="block-title">
        <span><?php echo $this->__('Select Your Currency') ?></span>
    </div>
    <div class="block-content dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="<?php echo $this->__('Select Your Currency') ?>">
            <span class="item-name">Currency: </span><span class="item-value"><?php echo $currency_code ?></span><span class="icon-dropdown"></span>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
                <?php if ($_code!=$this->getCurrentCurrencyCode()): ?>
                    <li><a tabindex="-1" href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"><?php echo $_code ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>            
        </ul>
    </div>
</div>
<?php endif; ?>
