 <?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<?php
$zonda = $this->helper('zonda');
?>
<div class="show-your-carts">
    <?php echo $this->__('Items in Cart ') ?><?php echo $this->__('(') ?><?php echo $this->helper('checkout/cart')->getSummaryCount(); ?><?php echo $this->__(')') ?>
</div>
 <div class="checkout-box clearfix">
     <?php if($this->getContinueShoppingUrl()): ?>
         <?php if (Mage::getStoreConfig('quickview/viewsetting/enableview') && !Mage::getStoreConfig('ajaxcart/addtocart/enablecategory')) {
             $continuShppingUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
         }
         else {
             $continuShppingUrl = $this->getContinueShoppingUrl();
         }?>
         <div class="contbox">
             <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $continuShppingUrl ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
             <span class="or"><?php echo $this->__('or') ?></span>
         </div>
     <?php endif; ?>
     <?php if(!$this->hasError()): ?>
         <div class="checkout-types">
             <?php foreach ($this->getMethods('methods') as $method): ?>
                 <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                     <div class="payment-method"><?php echo $methodHtml; ?></div>
                 <?php endif; ?>
             <?php endforeach; ?>
             <?php foreach ($this->getMethods('other_methods') as $method): ?>
                 <?php if ($othermethodHtml = $this->getMethodHtml($method)): ?>
                     <?php $othermethods = ($othermethodHtml == "" ? false : true); ?>
                 <?php endif; ?>
             <?php endforeach; ?>
             <?php if ($othermethods == true): ?>
                 <div class="other-methods-wrapper">
                 <a href="#" class="more-options-btn" id="more-options-btn">More Payment Options</a>
                 <div class="other-methods" id="other-methods">
             <?php endif; ?>
             <?php foreach ($this->getMethods('other_methods') as $method): ?>
                 <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                     <div><?php echo $methodHtml; ?></div>
                 <?php endif; ?>
             <?php endforeach; ?>
             <?php if ($othermethods == true): ?>
                 </div>
                 </div>
             <?php endif; ?>
         </div>
         <script type="text/javascript">
             //<![CDATA[
             jQuery(function() {
                 jQuery( "#more-options-btn" ).click(function(e) {
                     e.preventDefault();
                     jQuery(this).toggleClass('active');
                     jQuery( "#other-methods" ).toggle();
                 });
             });
             //]]>
         </script>
     <?php endif; ?>
 </div>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>" colspan="2"><span class="nobr"><?php echo $this->__('Product') ?></span></th>
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Wishlist') ?></span></th>
                        <?php endif ?>
                        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Code') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('QTY') ?></span></th>
                        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Price') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="last">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                            <!--<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>-->
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                        </td>
                    </tr>
                </tfoot>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            <script type="text/javascript">
               //<![CDATA[
                    jQuery(function($) {
                        $('.cart .button-up').click(function() {
                            $qty = $(this).parent().find('.qty');
                            qty = parseInt($qty.val()) + 1;
                            $qty.val(qty);
                        });
                    });
                    //]]>
            </script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <?php echo $this->getChildHtml('cspromo') ?>
        <div class="cart-set clearfix">
            <div class="shipping-container">
                <?php /* Extensions placeholder */ ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            </div>
            <div class="cartleftbox">
                <div class="coupon-box">
                    <?php echo $this->getChildHtml('coupon') ?>
                </div>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('risk-free')->toHtml(); ?>
            </div>
            <div class="total-container">
                <?php echo $this->getChildHtml('totals'); ?>
            </div>
        </div>
        <div class="btn-container clearfix">
            <div class="checkout-box checkout-box-bottom clearfix">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <?php if (Mage::getStoreConfig('quickview/viewsetting/enableview') && !Mage::getStoreConfig('ajaxcart/addtocart/enablecategory')) {
                        $continuShppingUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
                    }
                    else {
                        $continuShppingUrl = $this->getContinueShoppingUrl();
                    }?>
                    <div class="contbox">
                        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $continuShppingUrl ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                        <span class="or"><?php echo $this->__('or') ?></span>
                    </div>
                <?php endif; ?>
                <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                        <?php foreach ($this->getMethods('methods') as $method): ?>
                            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                <li><?php echo $methodHtml; ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                    <?php if ($othermethods == true): ?>
                        <div class="other-methods-bottom-wrapper">
                        <div class="other-methods-bottom" id="other-methods-bottom">
                            <span class="or-bottom-method"><?php echo $this->__('or') ?></span>
                    <?php endif; ?>
                    <?php foreach ($this->getMethods('other_bottom_methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <div><?php echo $methodHtml; ?></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($othermethods == true): ?>
                        </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>