<?php 
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct(); 
$_crossSellProducts = $_product->getCrossSellProducts();
//Default image size
$imgWidth = 125;
$imgHeight = 125;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
<?php if($_crossSellProducts && count($_crossSellProducts) > 0): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>

    <div id="crosssell-products-list" class="crosssell-products flexslider large-icons">
    <ul class="slides">
    <?php foreach ($_crossSellProducts as $_item): ?>

        <?php $_item = Mage::getModel('catalog/product')->load($_item->getId()); ?>
        <li class="item">
            <div class="cc-item-container clearfix">
                <div class="cc-img">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_item, 'small_image')) ?>">
                        <img src="<?php echo $zonda->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                    </a>
                </div>
                <div class="cc-shop">
                    <p class="cc-product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
                    <div class="price-review">
                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                        <?php endif; ?>
                    </div>
                    <div class="cc-description">
                            <?php echo $_item->getShortDescription() ?>
                    </div>
                    <div class="cart-container">
                        <?php echo $this->getPriceHtml($_item, true, '-crosssell') ?>
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php endif; ?>
                    </div>
                </div>
            </div>    
        </li>
    <?php endforeach; ?>
    </ul></div>

    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
    <script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
        $('#crosssell-products-list').flexslider({
            controlNav: true,
            directionNav: false,
            animation: 'slide',
            animationLoop: true,
            minItems: 1,
            maxItems: 1
        });
    });
    //]]>
    </script>
</div>
<?php endif; ?>