<?php
/**
 * Product short description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_description = $this->getProduct()->getShortDescription(); ?>
<?php if ($_description): ?>
    <h2><?php echo $this->__('Quick Overview') ?></h2>
    <div class="std">
        <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'short_description') ?>
    </div>
<?php endif; ?>