<?php
$productModel = Mage::getModel('catalog/product');
$product = $productModel->load(Mage::registry('current_product')->getId());
$finalPrice = $product->getFinalPrice();
?>
<!-- Facebook Conversion Code for Add To Cart -->
<script>(function() {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
    })();
    window._fbq = window._fbq || [];

    window._fbq('track', 'ViewContent', {
        content_type: 'product', //either 'product' or 'product_group'
        content_ids: ['<?php echo Mage::registry('current_product')->getId(); ?>'], //array of one or more product ids in the page
        value: <?php echo $finalPrice; ?>,    //OPTIONAL, but highly recommended
        currency: 'USD' //REQUIRED if you a pass value
    });

</script>