<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA at http://add-in-mage.com/support/presales/eula-community/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd. 
 * A separate installation package must be downloaded for each new Magento installation from Add In Mage web site.
 * You may modify the source code of the software to get the functionality you need for your store. 
 * You must retain, in the source code of any Derivative Works that You create, 
 * all copyright, patent, or trademark notices from the source code of the Original Work.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula-community/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>
<div class="addinmage-message">
	<h4><?php echo Mage::helper('toastnotifications')->__('Thank you for choosing Add In Mage:: Toast Notifications extension.')?></h4>
	<p><?php echo Mage::helper('toastnotifications')->__('Toast Notifications extension for Magento offers a new way of showing system notifications in Magento.')?></p>
</div>
