<script type="text/javascript">
    var $mcGoal = {'settings':{'uuid':'f526e9b07ce2e54e9317b88ce','dc':'us9'}};
    (function() {
        var sp = document.createElement('script'); sp.type = 'text/javascript'; sp.async = true; sp.defer = true;
        sp.src = ('https:' == document.location.protocol ? 'https://s3.amazonaws.com/downloads.mailchimp.com' : 'http://downloads.mailchimp.com') + '/js/goal.min.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sp, s);
    })();
</script>
