<?php
if(Mage::getURL('checkout/onepage/success') == Mage::helper('core/url')->getCurrentUrl()) {
//Get Order Number & Order Total
    $order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
    $items = $order->getAllVisibleItems();
    $orderId = $order->getIncrementId();
    $amount = number_format($order->getGrandTotal(), 2);
    $total = $order->getGrandTotal();
    $subtotal = $order->getSubtotal();
    $discount = $order->getDiscountAmount();
    $shippingAmount = $order->getShippingAmount();
    $taxAmount = $order->getTaxAmount();
    $affiliateTotal = ($subtotal + $discount);
    $billingAddress = $order->getBillingAddress();
    $customerName = $order->getCustomerName();
    $addressdata = $order->getBillingAddress()->getData();
    $billingStreet = $addressdata['street'];
    $billingStreet = explode("\n", $billingStreet);
    $billingStreet1 = $billingStreet[0];
    $billingStreet2 = $billingStreet[1];
    $billingZipCode = $order->getBillingAddress()->getPostcode();
    $billingCity = $order->getBillingAddress()->getCity();
    $billingRegion = $order->getBillingAddress()->getRegion();
    $billingCountry = $order->getBillingAddress()->getCountry();
    $shippingZipCode = $order->getShippingAddress()->getPostcode();
    $shippingCity = $order->getShippingAddress()->getCity();
    $shippingRegion = $order->getShippingAddress()->getRegion();
    $shippingCountry = $order->getShippingAddress()->getCountry();
    $customerEmail = $order->getCustomerEmail();
}
?>
<!--friendbuy tracking-->
<script>
    window['friendbuy'] = window['friendbuy'] || [];
    window['friendbuy'].push(['track', 'order',
        {
            id: '', //INPUT ORDER ID
            amount: '0.00', //INPUT ORDER AMOUNT
            //new_customer: false, //OPTIONAL, true if this is the customer's first purchase
            email: '' //INPUT EMAIL
        }
    ]);
</script>
<!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '1391558251146849');
    fbq('init', '547174985449849');
    fbq('init', '450917225103344');
    fbq('track', 'PageView');
    <?php if(Mage::getURL('checkout/cart') == Mage::helper('core/url')->getCurrentUrl()): ?>
    fbq('track', 'AddToCart');
    <?php endif; ?>
    <?php if(Mage::getURL('checkout/onepage') == Mage::helper('core/url')->getCurrentUrl()): ?>
    fbq('track', 'InitiateCheckout');
    <?php endif; ?>
    <?php if(Mage::getURL('checkout/onepage/success') == Mage::helper('core/url')->getCurrentUrl()): ?>
    fbq('track', 'Purchase', {value: '<?php echo $amount; ?>', currency: 'USD', order_id: '<?php echo $orderId; ?>'});
    <?php endif; ?>
</script>
<noscript><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=1391558251146849&ev=PageView&noscript=1"
        /><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=547174985449849&ev=PageView&noscript=1"
    /></noscript>
<!-- End Facebook Pixel Code -->

<!--Letterpress Pixel -->
<script type="text/javascript">
    ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
        p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
        };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.as
        ync=1;
        n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d1fc8wv8zag5ca.cloudfront.net/2.6.0/sp.js","letterpress"));
    window.letterpress('newTracker', 'mycljcoll', 't.getletterpress.com', {
        appId: '427635',
        cookieDomain: '.jenu.com',
        forceSecureTracker: '',
        contexts: {
            webPage: true,
            performanceTiming: true,
            gaCookies: true,
            geolocation: false
        }
    });
    window.letterpress('trackPageView');

    <?php if(Mage::getURL('checkout/onepage/success') == Mage::helper('core/url')->getCurrentUrl()): ?>

    window.letterpress('addTrans',
        '<?php echo $orderId; ?>', // order ID
        'Jenu', // affiliation or store name
        '<?php echo $amount; ?>', // grand total
        '<?php echo $taxAmount; ?>', // tax amount
        '<?php echo $shippingAmount; ?>', // shipping amount
        '<?php echo $shippingCity; ?>', // city
        '<?php echo $shippingRegion; ?>', // state or province
        '<?php echo $shippingCountry; ?>', // country
        'USD', // currency
        [{
        schema: 'iglu:com.getletterpress/address/jsonschema/1-0-0',
        data: {
            name: '<?php echo $customerName; ?>',
            street: '<?php echo $billingStreet1; ?>',
            street_2: '<?php echo $billingStreet2; ?>',
            zip: '<?php echo $billingZipCode; ?>',
            city: '<?php echo $billingCity; ?>',
            state: '<?php echo $billingRegion; ?>',
            country: '<?php echo $billingCountry; ?>',
            email: '<?php echo $customerEmail; ?>'
            }
        }]
    );

    <?php foreach($order->getAllVisibleItems() as $item): ?>
    <?php
    /** @var Mage_Catalog_Model_Product $product */
    $product = $item->getProduct();?>
        window.letterpress('addItem',
            '<?php echo $orderId; ?>', // order ID
            '<?php echo $product->getSku() ?>', // SKU
            '<?php echo $product->getName() ?>', // product name
            '', // category or variation
            '<?php echo round($item->getPrice(),2) ?>', // unit price
            '<?php echo round($item->getQtyOrdered()) ?>', // quantity
            'USD' // currency
        );
    <?php endforeach; ?>

    window.letterpress('trackTrans');

    <?php endif; ?>

</script>