<?php
//Get Order Number & Order Total
$order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
$orderId = $order->getIncrementId();
$amount = number_format($order->getGrandTotal(),2);
$total = $order->getGrandTotal();
$subtotal = $order->getSubtotal();
$discount = $order->getDiscountAmount();
$affiliateTotal = ($subtotal + $discount);
$billingAddress = $order->getBillingAddress();

?>
<!-- Facebook Conversion Code for Conversion Page -->
<script>
    (function () {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
    })();
    window._fbq = window._fbq || [];
    window._fbq.push(['track', '6020661552851', {'value': '<?php echo $amount; ?>', 'currency': 'USD'}]);
</script>
<noscript>
    <img height="1" width="1" alt="" style="display:none"
         src="https://www.facebook.com/tr?ev=6020661552851&amp;cd[value]=0.01&amp;cd[currency]=USD&amp;noscript=1"/>
</noscript>
<!-- Rev Content Conversion -->
<img src='https://trending.revcontent.com/ads/tracker.php?t=MzkxODs2OTU4'/>
<!--Google Adwords Pixel -->
<!-- Google Code for Order Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 955009829;
    var google_conversion_language = "en";
    var google_conversion_format = "2";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "ANN6CICVv1gQpZaxxwM";
    var google_conversion_value = 195.00;
    var google_conversion_currency = "USD";
    var google_remarketing_only = false;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/955009829/?value=195.00&amp;currency_code=USD&amp;label=ANN6CICVv1gQpZaxxwM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
<!--Taboola-->
<script type="text/javascript">
    window._tfa = window._tfa || [];
    _tfa.push({notify:"action", name: 'sale'});
</script>
<script src="//cdn.taboola.com/libtrc/jenu-sc/tfa.js"></script>
<img src="https://sp.analytics.yahoo.com/spp.pl?a=10001732416207&.yp=25800&js=no"/>
<!-- Glitter Network Offer Conversion: JeNu Ultrasonic Infuser System -->
<img src="//glitternetwork.go2cloud.org/SL1NE" width="1" height="1" />
<!-- // End Offer Conversion -->
<!--howlifeworks pixel-->
<img src='//www.howlifeworks.com/Lib/conversion_tracker.aspx?Adv_ID=1172' width='1' height='1' />
<!--end hwl pixel-->
<!--yahoo pixel-->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4023887"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>
<!--Outbrain pixel-->
<script language='JavaScript'>
    var OB_ADV_ID=27042;
    var scheme = (("https:" == document.location.protocol) ? "https://" : "http://");
    var str = '<script src="'+scheme+'widgets.outbrain.com/obtp.js" type="text/javascript"><\/script>';
    document.write(str);
</script>
<!--end outbrain pixel-->
<!-- affiliate -->
<img src="https://shareasale.com/sale.cfm?tracking=<?php echo $orderId; ?>&amount=<?php echo $affiliateTotal; ?>&transtype=sale&merchantID=58899" width="1" height="1">
<!-- AvantLink Affiliate -->
<script type="text/javascript">
    var _AvantMetrics = _AvantMetrics || [];
    _AvantMetrics.push(['order',{ order_id:'<?php echo $orderId; ?>', amount:'<?php echo $affiliateTotal; ?>', state:'<?php echo $billingAddress->getRegion(); ?>', country:'<?php echo $billingAddress->getCountry(); ?>' }]);
    _AvantMetrics.push(['item',{ track:'N', order_id:'[ORDER_ID]', parent_sku:'[ITEM_PARENT_SKU]', variant_sku:'[ITEM_VARIANT_SKU]', price:'[ITEM_PRICE]', qty:'[ITEM_QUANTITY]' }]);
</script>
<!--pinterest-->
<img height="1" width="1" alt="" src="https://ct.pinterest.com/?tid=ukDCI4BExWO"/>