<?php
//Get Order Number & Order Total
$order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
$orderId = $order->getIncrementId();
$amount = number_format($order->getGrandTotal(),2);
$total = $order->getGrandTotal();
$subtotal = $order->getSubtotal();
$discount = $order->getDiscountAmount();
$affiliateTotal = ($subtotal + $discount);
$billingAddress = $order->getBillingAddress();
$customerEmail = $order->getCustomerEmail();
?>
<!-- HowLifeWorks Conversion Pixel Start-->
<script type="text/javascript">
    (function(d) {
        var params =
        {
            pid: 29
            , details: "<?php echo $orderId; ?>"
        };
        var qs = Object.keys(params).reduce(function(a, k){ a.push(k + '=' + encodeURIComponent(params[k])); return a},[]).join('&');
        var i = d.createElement('iframe'); i.style = "width:1px;height:1px;display:none;";
        i.src = ('https:' === document.location.protocol? 'https' : 'http') + "://www.howlifeworks.com/Lib/Pixel.aspx?" + qs;
        d.body.appendChild(i);
    })(document);
</script>
<!-- HowLifeWorks Conversion Pixel End-->
<!--friendbuy tracking-->
<script>
    window['friendbuy'] = window['friendbuy'] || [];
    window['friendbuy'].push(['track', 'order',
        {
            id: '<?php echo $orderId; ?>', //INPUT ORDER ID
            amount: '<?php echo $amount; ?>', //INPUT ORDER AMOUNT
            //new_customer: false, //OPTIONAL, true if this is the customer's first purchase
            email: '<?php echo $customerEmail; ?>' //INPUT EMAIL
        }
    ]);
</script>
<!-- Rev Content Conversion -->
<img src='https://trending.revcontent.com/ads/tracker.php?t=MzkxODs2OTU4' style="visibility:hidden;position: absolute;"/>
<!--Google Adwords Pixel -->
<!-- Google Code for Order Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 955009829;
    var google_conversion_language = "en";
    var google_conversion_format = "2";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "ANN6CICVv1gQpZaxxwM";
    var google_conversion_value = <?php echo $amount; ?>;
    var google_conversion_currency = "USD";
    var google_remarketing_only = false;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/955009829/?value=<?php echo $amount; ?>&amp;currency_code=USD&amp;label=ANN6CICVv1gQpZaxxwM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
<!--Taboola-->
<script type="text/javascript">
    window._tfa = window._tfa || [];
    _tfa.push({notify:"action", name: 'sale'});
</script>
<script src="//cdn.taboola.com/libtrc/jenu-sc/tfa.js"></script>
<img src="https://sp.analytics.yahoo.com/spp.pl?a=10001732416207&.yp=25800&js=no"/>
<!-- Glitter Network Offer Conversion: JeNu Ultrasonic Infuser System -->
<img src="//glitternetwork.go2cloud.org/SL1NE" width="1" height="1" style="visibility:hidden;position: absolute;"/>
<!-- // End Offer Conversion -->
<!--howlifeworks pixel-->
<img src='//www.howlifeworks.com/Lib/conversion_tracker.aspx?Adv_ID=1172' width='1' height='1' style="visibility:hidden;position: absolute;" />
<!--end hwl pixel-->
<!--yahoo pixel-->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4023887"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>
<!--Outbrain pixel-->
<script language='JavaScript'>
    var OB_ADV_ID=27042;
    var scheme = (("https:" == document.location.protocol) ? "https://" : "http://");
    var str = '<script src="'+scheme+'widgets.outbrain.com/obtp.js" type="text/javascript"><\/script>';
    document.write(str);
</script>
<!--end outbrain pixel-->
<!-- Offer Conversion: Jenu Ultrasonic Infuser -->
<iframe src="https://grapevine.go2cloud.org/aff_l?offer_id=75" scrolling="no" frameborder="0" width="1" height="1"></iframe>
<!-- // End Offer Conversion -->
<!--pinterest-->
<img height="1" width="1" alt="" src="//ct.pinterest.com/?tid=ukDCI4BExWO"/>
<img height="1" width="1" style="display:none;" alt="" src="//ct.pinterest.com/?tid=UbL6sjFwoVJ"/>
<img height="1" width="1" style="display:none;" alt="" src="//ct.pinterest.com/?tid=w0UUEimk350&value=0.00&quantity=1"/>
<!-- Start Bizrate POS Code -->
<script language="JavaScript">
    // var passin_x =''; //comment out to default center or adjust horizontal position by pixel
    // var passin_y =''; //comment out to default center or adjust vertical position by pixel
    // var orderId='';
    // var z_index =''; //default 1,000,000
    // var cartTotal='';
    // var billingZipCode='';
    // Pass up to 5 products from customer shopping cart
    var productsPurchased= 'URL=^SKU=^GTIN=^PRICE=|URL=^SKU=^GTIN=^PRICE=|URL=^SKU=^GTIN=^PRICE=|URL=^SKU=^GTIN=^PRICE=|URL=^SKU=^GTIN=^PRICE=';
</script>
<script type="text/javascript" src="//eval.bizrate.com/js/pos_298445.js">
</script>
<!-- End Bizrate POS Code -->
<!-- referralcandy tracking -->
<script type='text/javascript'>
    !function(d,s) {
        var rc = d.location.protocol + "//go.referralcandy.com/purchase/tphut1bq2nv6r4bo9tg6cgmpi.js";
        var js = d.createElement(s);
        js.src = rc;
        var fjs = d.getElementsByTagName(s)[0];
        fjs.parentNode.insertBefore(js,fjs);
    }(document,"script");
</script>
<!-- end referral candy tracking-->
<!-- w4 equedia pixel -->
<iframe width='1' height='1' frameborder='0' src='//www.trkedoty.com/rd/ipx.php?sid=14644&transid=<?php echo $orderId; ?>'></iframe>