<?php 
$store = Mage::app()->getStore();
$code  = $store->getCode();
$enable = Mage::getStoreConfig('filterproducts/bestseller/active',$code);
?>
<?php if($enable == 1) { ?>
<div class="block block-bestseller">
    <div class="block-title">
        <strong><span><?php echo Mage::getStoreConfig('filterproducts/bestseller/title',$code); ?></span></strong>
    </div>
    <div class="block-content">
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_productCollection->addAttributeToSelect('news_from_date')
        ->addAttributeToSelect('news_to_date');
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="flex-bestseller" class="category-products">
    <?php $_iterator = 0; ?>
    <ul class="products-grid slides" id="products-list">
    <?php foreach ($_productCollection as $_prod): ?>
    <?php
        $_product = Mage::getModel('catalog/product')->load($_prod->getId());
    ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div class="item-inner">
                <?php // Product Image ?>
                <div class="product-image" hover_img="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(200) ?>" base_img="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(200) ?>" >
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <div class="reviews-wrap">
                        <?php echo $this->getReviewsSummaryHtml($_product,'short') ?>
                    </div>
                </div>
                <?php// label for products ?>
                <?php 
                        $labels_tl = ''; $labels_tr = '';
                        
                        // New Product 
                        $newsFromDate = $_product->getNewsFromDate();
                        $newsToDate = $_product->getNewsToDate();
                        $new_html= '';
                        if ($newsFromDate && $newsToDate && Mage::app()->getLocale()->IsStoreDateInInterval(Mage::app()->getStore(), $newsFromDate, $newsToDate)){
                            $new_html = '<div class="labels new-pro"></div>';
                            $labels_tl = $new_html;
                        }
                        // Special Product
//                            
                        $specialPriceFromDate = $_product->getSpecialFromDate();
                        $specialPriceToDate = $_product->getSpecialToDate();
                        $sales_html = '';
                        if ($specialPriceFromDate && $specialPriceToDate && Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $specialPriceFromDate, $specialPriceToDate)) {
                            $price = $_product->getPrice();
                            $specialprice = $_product->getSpecialPrice();
                            $sales_html = '<div class="labels spec-pro"><div class="spec-pro-text">'.round(($specialprice - $price) / $price * 100).'% off</div></div>';
                            $labels_tl = $sales_html;
                        }
                        
                        if ($labels_tl)
                            echo $labels_tl;
                        ?>
            <?php // Product description ?>
                <div class="price-review">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div class="actions clearfix">
                        <?php if($_product->isSaleable()): ?>
                            <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else : ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>showOptions('<?php echo $_product->getId()?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                            <?php endif;?>
                        <?php else: ?>
                            <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                        <?php endif; ?>
                        <span class="add-to-links">
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                        </span>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <!--<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>-->
    <script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
        $('#flex-bestseller').flexslider({
            controlNav: false,
            animation: 'slide',
            animationLoop: true,
            slideshowSpeed: 2000,
            nextText: "<i class='icon-brand-arrow'>&nbsp;</i>",
            prevText: "<i class='icon-brand-arrow'>&nbsp;</i>"
        });
    });
    //]]>
    </script>
</div>
<?php endif; ?>

    </div>
</div>

<?php }  ?>