<?php
/**
 * @see Mage_Page_Block_Template_Links_Block
 */
?>
<?php
    $classes = '';
            
    if ($this->getIsFirst())
    {
        $classes .= 'first';
    }
    
    if ($this->getIsLast())
    {
        $classes .= ' last';
    }
    $label = $this->getLabel();
    $icon_class = strtolower(current(explode("(", preg_replace('/\s+/', '', $label), 2)));
    $title = current(explode("(", $label, 2));
    $count = (int)str_replace($title.'(', '', $label);
    $count = $count > 0 ? '<span class="count">(' . $count . ')</span>' : '';
?>
<li <?php if($classes): ?>class="<?php echo $classes; ?>"<?php endif;?> <?php echo $this->getLiParams() ?>><?php echo $this->getBeforeText() ?><a href="<?php echo $this->getLinkUrl() ?>" title="<?php echo $this->getTitle() ?>" <?php echo $this->getAParams() ?>><span><?php echo $title . $count; ?></span></a><?php echo $this->getAfterText() ?></li>