<div class="content-header">
    <h3 class="icon-head head-products"><?php echo $this->getHeader() ?></h3>
	 
    <p class="content-buttons form-buttons"><?php echo $this->getSaveButtonHtml() ?> </p>
</div>


<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="product_edit_form" enctype="multipart/form-data" >

<?php echo $this->getBlockHtml('formkey')?>
<div id="surya" style="display:none"></div>
<input type="hidden" name ="formid" value ="<?php echo Mage::app()->getRequest()->getParam('id');?>">

<div class="entry-edit custom-options product-custom-options">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('catalog')->__('Custom Options') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
		<?php echo $this->getOptionsBoxHtml() ?>
    </div>
</div>

</form>

<script type="text/javascript">
//<![CDATA[
    var productTemplateSyntax = /(^|.|\r|\n)({{(\w+)}})/;
    var productForm = new varienForm('product_edit_form', '<?php echo $this->getValidationUrl() ?>');
    productForm._processValidationResult = function(transport) {
        var response = transport.responseText.evalJSON();
        if (response.error){
            if (response.attribute && $(response.attribute)) {
                $(response.attribute).setHasError(true, productForm);
                Validation.ajaxError($(response.attribute), response.message);
                if (!Prototype.Browser.IE){
                    $(response.attribute).focus();
                }
            }
            else if ($('messages')) {
                $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
            }
        }
        else{
            productForm._submit();
        }
    };
    function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, productTemplateSyntax);
        var url = template.evaluate({tab_id:product_info_tabsJsTabs.activeTab.id});
        productForm.submit(url);
    }
    function setSettings(urlTemplate, setElement, typeElement) {
        var template = new Template(urlTemplate, productTemplateSyntax);
        setLocation(template.evaluate({attribute_set:$F(setElement),type:$F(typeElement)}));
    }

     function setSuperSettings(urlTemplate, attributesClass, validateField) {
        var attributesFields = $$('.' + attributesClass);
        var attributes = Form.serializeElements(attributesFields, true).attribute;
        if(typeof attributes == 'string') {
            attributes = [attributes];
        }

        if(!attributes) {
            $(validateField).value = 'no-attributes';
        } else {
            $(validateField).value = 'has-attributes';
        }

        if (productForm.validator.validate()) {
            var template = new Template(urlTemplate, productTemplateSyntax);
            var url = template.evaluate({
                attributes: encode_base64(attributes.join(',')).replace(new RegExp('/','g'),'%2F').replace(new RegExp('=','g'),'%3D')
            });
            setLocation(url);
        }
    }

    function checkMaxLength(Object, MaxLen)
    {
        if (Object.value.length > MaxLen-1) {
            Object.value = Object.value.substr(0, MaxLen);
        }
        return 1;
    }
	
	function validateForm()
	{	
		alert(1);
		document.getElementById('product_option_1_type').disabled = false;
		document.getElementById('product_option_1_is_require').disabled = false;
		return false;
	}

// Event.observe(window, 'load', function() {
    // var objName = '<?php echo $this->getSelectedTabId() ?>';
    // if (objName) {
        // obj = $(objName);
       //IE fix (bubbling event model)
        // product_info_tabsJsTabs.setSkipDisplayFirstTab();
        // product_info_tabsJsTabs.showTabContent(obj);
    // }
    // Product.AttributesBridge.setTabsObject(product_info_tabsJsTabs);
// });

Validation.addAllThese([
    ['validate-super-product-attributes', '<?php echo Mage::helper('catalog')->__('Please select one or more attributes.') ?>', function(v) {
                return (v != "no-attributes");
            }]]);
//]]>
</script>
<!--
<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
//show error message
if ($('price_type')) {
    if ($('price_type').value == '0' && $('dynamic-price-warrning')) {
        $('dynamic-price-warrning').show();
    }
}
</script>
 -->