<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (!Mage::getSingleton('customer/session')->isLoggedIn() || !Mage::helper('awraf/config')->isInviteAllowed()): ?>
    <a class="button btn-login" id="btn-login" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><span><?php echo $this->__('Login to Refer a Friend') ?></span></a>
<?php else: ?>
    <?php
    $buttonId = uniqid( rand(0, 1000) );
    ?>
    <button class="button btn-cart" id="referafriend-button<?php echo $buttonId;?>" type="button"><span><span><?php echo $this->__('Refer a Friend') ?></span></span></button>
    <script type="text/javascript">
        document.observe('dom:loaded', function () {
            new Referafriend($('referafriend-button<?php echo $buttonId;?>'), '<?php echo $this->helper('awraf')->getReferafriendUrl() ?>');
        });
    </script>
<?php endif;?>