<!-- SocialShare - OpenGraphTags Head -->
<?php if (Mage::getStoreConfig('opengraphtags/facebook/fb_appid') != ''): ?>
<meta property="fb:app_id" content="<?php echo trim(Mage::getStoreConfig('opengraphtags/facebook/fb_appid'));?>" />
<?php endif; ?>
<?php if (Mage::getStoreConfig('opengraphtags/facebook/fb_admins') != ''): ?>
<meta property="fb:admins" content="<?php echo trim(Mage::getStoreConfig('opengraphtags/facebook/fb_admins'));?>" />
<?php endif; ?>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
<meta property="og:type" content="product" />
<?php $product = Mage::registry('current_product');
if ($product): ?>
<meta property="og:title" content="<?php echo trim($product->getName()); ?>"/>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init($product, 'image');?>"/>
<?php elseif (!$product): ?>
<meta property="og:image" content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>content/fb-image-default.jpg"/>
<meta property="og:image:width" content="1000" />
<?php endif; ?>
<!-- SocialShare - OpenGraphTags Head END -->
