<?php if (!$this->getHideTitle()): ?>
    <p><strong><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></strong></p>
<?php endif;?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<dl class="cards-list">
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
        <dt><?php echo sprintf($this->__('Credit Card %s'), $key + 1); ?></dt>
    <?php endif;?>

    <dd <?php if ($showCount):?> class="offset"<?php endif;?>>
    <table class="info-table">
        <tbody>
        <?php foreach ($card as $_label => $_value):?>
        <tr>
            <th><?php echo $this->escapeHtml($_label)?>:</th>
            <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </dd>
<?php endforeach; ?>
</dl>