<?php 
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
//Default image size
$imgWidth = 100;
$imgHeight = 100;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="block block-products block-list">
        <div class="block-title <?php if ($_products->getSize() > 4) echo 'slider-title'; ?>">
            <strong><span><?php echo $this->__('New Products') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <div id="widget-new-products-<?php echo $suffix; ?>" class="mini-products-list flexslider"><ul class="slides">
            <?php
            $i = 0; 
            foreach ($_products->getItems() as $_product): ?>
                <?php if ($i % 4 == 0) : ?><li><?php endif; ?>
                <div class="item clearfix">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <img src="<?php echo $zonda->getImage($_product, $imgWidth, $imgHeight, 'thumbnail'); ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <?php echo $this->getReviewsSummaryHtml($_product, true) ?>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-'.$suffix) ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </div>
                <?php if ($i % 4 == 3) : ?></li><?php endif; ?>
            <?php 
            $i++;
            endforeach; ?>
            <?php if ($i % 4 != 0) : ?></li><?php endif; ?>
            </ul></div>
            <script type="text/javascript">decorateList('widget-new-products-<?php echo $suffix; ?>', 'none-recursive')</script>
            <script type="text/javascript">
            //<![CDATA[
                jQuery(function($) {
                    $('#widget-new-products-<?php echo $suffix; ?>').flexslider({
                        controlNav: false,
                        animation: 'slide'
                    });
                });
            //]]>
            </script>
        </div>
    </div>
</div>
<?php endif; ?>
