<?php 
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
//Default image size
$imgWidth = 100;
$imgHeight = 100;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="block block-list">
        <div class="block-title <?php if ($_products->getSize() > 6) echo 'slider-title'; ?>">
            <strong><span><?php echo $this->__('New Products') ?></span></strong>
        </div>
        <div class="block-content text-center">
            <?php $suffix = $this->getNameInLayout(); ?>
            <div id="widget-new-products-<?php echo $suffix; ?>" class="mini-products-images-list flexslider"><ul class="slides">
            <?php 
            $i = 0;
            foreach ($_products->getItems() as $_product): ?>
                <?php if ($i % 6 == 0) : ?><li><?php endif; ?>
                <div class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <img src="<?php echo $zonda->getImage($_product, $imgWidth, $imgHeight, 'thumbnail'); ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                </div>
                <?php if ($i % 6 == 5) : ?></li><?php endif; ?>
            <?php 
            $i++;
            endforeach; ?>
            <?php if ($i % 6 != 0) : ?></li><?php endif; ?>
            </ul></div>
            <script type="text/javascript">decorateList('widget-new-products-<?php echo $suffix; ?>', 'none-recursive')</script>
            <script type="text/javascript">
                jQuery(document).ready(function($) {
                    $('#widget-new-products-<?php echo $suffix; ?>').flexslider({
                        controlNav: false,
                        animation: 'slide'
                    });
                });
            </script>
        </div>
    </div>
</div>
<?php endif; ?>
