<div class="error-area">
            <div class="error-content">
                <div class="text-container">
                    <div class="container">
                        <h2><?php echo $this->__("Page can not be found")?></h2>
                    </div>
                </div>                
                <div class="number-container">
                    <div class="container">
                        <img src="<?php echo $this->getSkinUrl('images/backgrounds/404_text.png'); ?>"/>
                    </div>
                </div>
                <div class="text-container">
                    <div class="container">
                        <div class="search-form">
                            <div class="message-text">
                                <?php echo $this->__('Go to our home page or go back to previous page.') ?>
                            </div>
                            <?php
                            $catalogSearchHelper =  $this->helper('catalogsearch');
                            ?>
                            <form id="error_search_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
                                <div class="form-search">
                                    <label for="error_search"><?php echo $this->__('Search:') ?></label>
                                    <input id="error_search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"/>
                                    <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"></button>
                                    <div id="error_search_autocomplete" class="search-autocomplete"></div>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        var searchForm = new Varien.searchForm('error_search_form', 'error_search', '<?php echo $this->__('Search here...') ?>');
                                        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'error_search_autocomplete');
                                    //]]>
                                    </script>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>                
        </div>