<?php
$zonda = $this->helper('zonda');
$blockIds = $zonda->getAdsBlockIds();
if (count($blockIds) > 0):
?>
<div class="block block-zonda-ads">
    <div class="block-content">
        <div id="zonda-ads" class="flexslider">
            <ul class="slides">
                <?php foreach ($blockIds as $blockId) : ?>
                    <li>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml(); ?>
                    </li>
                <?php
                $i++; 
                endforeach; ?>
            </ul>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            jQuery(function($) {
                $('#zonda-ads').flexslider({
                    directionNav: false,                    
                    slideshowSpeed: 4000
                });
            });
        //]]>
        </script>
    </div>
</div>
<?php endif; ?>