<?php
$zonda = $this->helper('zonda');
 if ($this->getLayout()->createBlock('cms/block')->setBlockId('block_contact_details')):
?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span>Contact Info</span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_contact_details')->toHtml(); ?>
    </div>
</div>
<?php endif; ?>
