<?php
$zonda = $this->helper('zonda');
$gmap = $zonda->getGMap();
if ($gmap):
    $gmap_maker = $zonda->getGmapMaker();
    if (!$gmap_maker) {        
        $gmap_maker = $this->getSkinUrl('/images/icons/icon_gmap_marker.png');
    }
?>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript">
    jQuery.noConflict();
</script>
    <script>
    //<![CDATA[
    var store = new google.maps.LatLng(<?php echo $gmap['lat'] ?>, <?php echo $gmap['lng'] ?>);
    var marker;
    var map;

    function initialize() {
        var mapOptions = {
            zoom: 15,
            mapTypeControl:false,
            streetViewControl: false,
            zoomControl:false,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            center: store
        };

        map = new google.maps.Map(document.getElementById('block-map'), mapOptions);

        marker = new google.maps.Marker({
            map: map,
            draggable: false,            
            animation: google.maps.Animation.DROP,
            position: store,
            icon: '<?php echo $gmap_maker ?>'
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
    google.maps.event.addDomListener(window, 'resize', initialize);
    //]]>
    </script>
    <div id="block-map"></div>
<?php endif; ?>
