<?php
$zonda = $this->helper('zonda');
$containerClass = $zonda->getContainerClass();
$rowClass = $zonda->getRowClass();
$spanClass = $zonda->getSpanClass();

$tt_result = $this->getTweets();
$tt_config = $zonda->getTwitterConfig();
$tt_slider_class = $tt_config['profile_image'] ? 'twitter-slider1' : 'twitter-slider2';
if ($tt_result) : ?>
<div id="twitter-footer-slider" class="<?php echo $tt_slider_class ?> flexslider">
    <ul class="slides">
    <?php $i = 0; ?>
    <?php foreach ($tt_result as $tweet) : ?>
        <?php if ($i % 2 == 0) : ?><li><?php endif; ?>            
            <p class="text"><?php echo $this->processString($tweet->text); ?></p>
            <div class="date"><?php echo $this->__('about ') ?><?php 
            $created_at = $tweet->created_at; 
            $created = strtotime($created_at);
            $now = strtotime('now');
            $diff = $now - $created;
            $years = floor($diff / (365*60*60*24));
            $months = floor($diff / (30*60*60*24));
            $days = floor($diff / (60*60*24));
            $hours = floor($diff / (60*60));    
            $minutes  = floor($diff / 60);
            $seconds = $diff; 
            if ($days != 0)
                echo $days . $this->__(' days ago');
            else {
                if ($hours != 0)
                    echo $hours . $this->__(' hours ago');
                else 
                    echo $minutes . $this->__(' minutes ago');
            }
            ?></div>
        <?php if ($i % 2 == 1) : ?></li><?php endif; ?>
    <?php $i++; endforeach; ?>
    <?php if ($i % 2 != 0) : ?></li><?php endif; ?>
    </ul>
    <script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
        $('#twitter-footer-slider').flexslider({
            controlNav: false,
            directionNav: false,
            animation: 'slide',
            animationLoop: true
        });
    });
    //]]>
    </script>
</div>
<?php endif; ?>