<?php
$zonda = $this->helper('zonda');
$tt_result = $this->getTweets();
$tt_config = $zonda->getTwitterConfig();
if ($tt_result && $zonda->getConfig('twitter/show_in_bottom')) : ?>
<div class="container clearfix">
<div id="twitter-slider" class="twitter-slider">
    <div class="twitter-container">
    <div class="twitter-slider-arrow"></div>
    <div class="twitter-content">
    <ul class="bxslider">
    <?php foreach ($tt_result as $tweet) : ?>
        <li>
            <p class="text"><?php echo $this->processString($tweet->text); ?></p>
            <div class="date"><?php 
            $created_at = $tweet->created_at; 
            $created = strtotime($created_at);
            $now = strtotime('now');
            $diff = $now - $created;
            $years = floor($diff / (365*60*60*24));
            $months = floor($diff / (30*60*60*24));
            $days = floor($diff / (60*60*24));
            $hours = floor($diff / (60*60));    
            $minutes  = floor($diff / 60);
            $seconds = $diff; 
            if ($days != 0)
                echo $days . $this->__(' days ago');
            else {
                if ($hours != 0)
                    echo $hours . $this->__(' hours ago');
                else 
                    echo $minutes . $this->__(' minutes ago');
            }
            ?></div>
        </li>
    <?php endforeach; ?>
    </ul>
    </div>
    </div>
    <div class="twitter-nav-container">
	<span id="tt-slider-prev"></span>
	<span id="tt-slider-next"></span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
	var twitter_slider_bottom = $('#twitter-slider .bxslider').bxSlider({nextSelector:'#tt-slider-next', prevSelector: '#tt-slider-prev',nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false, auto:true});        
    });
    //]]>
    </script>        
</div>
<div class="twitter-icon"></div>
</div>
<?php endif; ?>