<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php 
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();

//Default image size
$imgWidth = 228;
$imgHeight = 228;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];
    
$_helper = $this->helper('catalog/output'); 
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="widget-title">
        <h2><?php echo $this->__('New Products') ?></h2>
    </div>
    <div class="widget-products">
        <ol class="products-list">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <?php // Product Image & Price ?>
                <div class="product-image<?php if (!$b['product']['price_on_image']) echo ' no-price' ?>">
                    <?php 
                    if ($b['category']['hover_image'])
                        $hoverImgHtml = $zonda->getHoverImageHtml($_product, $imgWidth, $imgHeight); 
                    ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img<?php if ($hoverImgHtml) echo ' class="primary-image"'; ?> src="<?php echo $zonda->getImage($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                        <?php echo $hoverImgHtml; ?>
                        <?php 
                        $labels_tl = ''; $labels_tr = ''; $labels_bl = ''; $labels_br = '';
                        if ($b['product']['new_label']) {
                            // New Product 
                            $newsFromDate = $_product->getNewsFromDate();
                            $newsToDate = $_product->getNewsToDate();
                            $new_html = '';
                            if ($newsFromDate && $newsToDate && Mage::app()->getLocale()->IsStoreDateInInterval(Mage::app()->getStore(), $newsFromDate, $newsToDate))
                                $new_html = '<div class="new ' . $b['product']['new_label_type'] . '">'. $this->__('New') .'</div>';
                            switch ($b['product']['new_label_pos']) {
                                case 'top-right': $labels_tr .= $new_html; break;
                                case 'bottom-left': $labels_bl .= $new_html; break;
                                case 'bottom-right': $labels_br .= $new_html; break;
                                default: $labels_tl .= $new_html; break;
                            }
                        }
                        if ($b['product']['sale_label']) {
                            // Special Product
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();
                            $sales_html = '';
                            if ($specialPriceFromDate && $specialPriceToDate && Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $specialPriceFromDate, $specialPriceToDate)) {
                                $price = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $sales_html = '<div class="sales ' . $b['product']['sale_label_type'] . '">' . round(($specialprice - $price) / $price * 100) . '%</div>';
                            }
                            switch ($b['product']['sale_label_pos']) {
                                case 'top-right': $labels_tr .= $sales_html; break;
                                case 'bottom-left': $labels_bl .= $sales_html; break;
                                case 'bottom-right': $labels_br .= $sales_html; break;
                                default: $labels_tl .= $sales_html; break;
                            }
                        }
                        if ($labels_tl) echo '<div class="labels top-left">' . $labels_tl . '</div>';
                        if ($labels_tr) echo '<div class="labels top-right">' . $labels_tr . '</div>';
                        if ($labels_bl) echo '<div class="labels bottom-left">' . $labels_bl . '</div>';
                        if ($labels_br) echo '<div class="labels bottom-right">' . $labels_br . '</div>';
                        ?>
                    </a>
                    <?php if ($b['product']['price_on_image']) : ?>
                        <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                    <?php endif; ?>
                </div>
                <?php // Product description ?>
                <div class="product-shop">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h3>
                    
                    <?php if (!$b['product']['price_on_image']) : ?>
                    <div class="price-review">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php endif; ?>
                        
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                    
                    <?php if (!$b['product']['price_on_image']) : ?></div><?php endif; ?>
                    
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                    <div class="actions clearfix">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                        <?php endif; ?>
                        <span class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                        </span>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
