<?php if (!is_null($this->getProductId())): ?>
    <?php $_items = $this->getReviewsCollection()->getItems(); ?>
    <?php if (count($_items)): ?>
	<dl>
	    <?php foreach ($_items as $_review): ?>
	        <dd class="comments-item">
	    	<div class="review-row clearfix">
			<?php
			$_votes = $_review->getRatingVotes();
			$_sumRating = 0;
			if (count($_votes)):
			    foreach ($_votes as $_vote):
				$_sumRating += $_vote->getPercent();
			    endforeach;
			    $rating = $_sumRating / (count($_votes));
			endif;
			?>
	    	    <div class="ratings">
	    		<div class="rating-box">
	    		    <div class="rating" style="width:<?php echo $rating ?>%;"></div>
	    		</div>
	    	    </div>
	    	    <span class="review-title"><?php echo $this->htmlEscape($_review->getTitle()) ?></span>
	    	</div>
	    	<p class="name_date">
			<?php echo $this->__('by ') ?>
	    	    <span class="by_name">
			    <?php echo $this->escapeHtml($_review->getNickname()) ?> 
	    	    </span>
			<?php echo $this->__('on ') ?>
	    	    <span class="on_date">
			    <?php echo $this->__($this->formatDate($_review->getCreatedAt()), 'long') ?>
	    	    </span>
	    	</p>
		    <?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>
	    	<br>




	        </dd>
	        <div class="line-separator2"></div>
	    <?php endforeach; ?>
	</dl>
	<?php echo $this->getChildHtml('toolbar') ?>
	<p class="reviews-disclaimer"><?php echo $this->__('All testimonials are submitted by real customers, are their own opinions and are unedited. Results may vary.') ?></p>
    <?php elseif ($this->getParentBlock()): ?>
	<?php echo $this->getParentBlock()->getReviewsSummaryHtml($this->getProduct(), 'short', true) ?>
    <?php endif; ?>
    <?php echo $this->getChildHtml('review_form') ?>
<?php endif; ?>