<script src="/js/eternal/jquery/jquery.bxslider.min.js"></script>
<link href="/skin/frontend/zonda/default/css/jquery/jquery.bxslider.css" rel="stylesheet" />
<link href="/skin/frontend/zonda/default/css/bootstrap.min.css" rel="stylesheet" />
<link href="/skin/frontend/zonda/default/css/eternal/customslideshow.css" rel="stylesheet" />

<div id="custom">
    <div class="container">
        <div class="row right">
            <div class="col-md-12">
                <div class="bx-container">
                    <ul class="bxslider">
                        <li><a href="/products.html/"><img src="/media/wysiwyg/homepage-feature1b.jpg" /></a></li>
                        <li><a href="/ultrasound-101/"><img src="/media/wysiwyg/homepage-feature2b.jpg" /></a></li>
                        <li><a href="/dr-sonia-batra/"><img src="/media/wysiwyg/homepage-feature3b.jpg" /></a></li>
                    </ul>

                    <div class="bx-controls bx-has-controls-direction">
                        <div class="bx-controls-direction">
                            <a class="bx-prev" href="#">
                                <i class="icon-brand-arrow">&nbsp;</i>
                            </a>
                            <a class="bx-next" href="#">
                                <i class="icon-brand-arrow">&nbsp;</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="big-image">
        <div class="big-text">
            <p>The First Universal Ultrasound Skin Care Delivery System</p>
            <p>Designed to Increase the Benefits of Your Favorite Skin Care Products</p>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function(){
        jQuery("#custom").fadeIn();
        var slider = jQuery('.bxslider').bxSlider({
            mode: 'vertical',
            slideMargin: 10,
            pager: false,
            nextSelector: "bx-next",
            prevSelector: "bx-prev",
            nextText: "<i class='icon-brand-arrow'>&nbsp;</i>",
            prevText: "<i class='icon-brand-arrow'>&nbsp;</i>"
        });

        jQuery(".bx-prev").click(function(){
            slider.goToPrevSlide();
            return false;
        });

        jQuery(".bx-next").click(function(){
            slider.goToNextSlide();
            return false;
        });
    });
</script>