<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php 
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();

//Default image size
$imgWidth = 228;
$imgHeight = 228;

//Aspect Ratio
if ($b['product']['aspect_ratio'])
    $imgHeight = $imgWidth * $b['product']['image_ratio'];

if($this->getItemCount()): ?>
<div class="crosssell box-cross-sell">
    <h2 class="subtitle"><span class="inline-title"><?php echo $this->__('Cross Sells') ?></span><?php if ($this->getItemCount() > 2) echo '<div class="line"></div>'; ?></h2>
    <p class="desc"><?php echo $this->__('Based on your selection, you may be interested in the following items.') ?></p>
    
    <div id="crosssell-products-list" class="crosssell-products products-grid flexslider large-icons"><ul class="slides">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item"><div class="item-inner">
            <div class="product-image">
                <?php 
                if ($b['category']['hover_image'])
                    $hoverImgHtml = $zonda->getHoverImageHtml($_item, $imgWidth, $imgHeight); 
                ?>
                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_item, 'small_image')) ?>">
                    <img<?php if ($hoverImgHtml) echo ' class="primary-image"'; ?> src="<?php echo $zonda->getImage($_item, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                    <?php echo $hoverImgHtml; ?>
                    <?php 
                    $labels_tl = ''; $labels_tr = ''; $labels_bl = ''; $labels_br = '';
                    if ($b['product']['new_label']) {
                        // New Product 
                        $newsFromDate = $_item->getNewsFromDate();
                        $newsToDate = $_item->getNewsToDate();
                        $new_html = '';
                        if ($newsFromDate && $newsToDate && Mage::app()->getLocale()->IsStoreDateInInterval(Mage::app()->getStore(), $newsFromDate, $newsToDate))
                            $new_html = '<div class="new ' . $b['product']['new_label_type'] . '">'. $this->__('New') .'</div>';
                        switch ($b['product']['new_label_pos']) {
                            case 'top-right': $labels_tr .= $new_html; break;
                            case 'bottom-left': $labels_bl .= $new_html; break;
                            case 'bottom-right': $labels_br .= $new_html; break;
                            default: $labels_tl .= $new_html; break;
                        }
                    }
                    if ($b['product']['sale_label']) {
                        // Special Product
                        $specialPriceFromDate = $_item->getSpecialFromDate();
                        $specialPriceToDate = $_item->getSpecialToDate();
                        $sales_html = '';
                        if ($specialPriceFromDate && $specialPriceToDate && Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $specialPriceFromDate, $specialPriceToDate)) {
                            $price = $_item->getPrice();
                            $specialprice = $_item->getSpecialPrice();
                            $sales_html = '<div class="sales ' . $b['product']['sale_label_type'] . '">' . round(($specialprice - $price) / $price * 100) . '%</div>';
                        }
                        switch ($b['product']['sale_label_pos']) {
                            case 'top-right': $labels_tr .= $sales_html; break;
                            case 'bottom-left': $labels_bl .= $sales_html; break;
                            case 'bottom-right': $labels_br .= $sales_html; break;
                            default: $labels_tl .= $sales_html; break;
                        }
                    }
                    if ($labels_tl) echo '<div class="labels top-left">' . $labels_tl . '</div>';
                    if ($labels_tr) echo '<div class="labels top-right">' . $labels_tr . '</div>';
                    if ($labels_bl) echo '<div class="labels bottom-left">' . $labels_bl . '</div>';
                    if ($labels_br) echo '<div class="labels bottom-right">' . $labels_br . '</div>';
                    ?>
                </a>
                <?php if ($b['product']['price_on_image']) : ?>
                    <?php echo $this->getPriceHtml($_item, true) ?>
                <?php endif; ?>
            </div>
            
            <?php if (!$b['product']['price_on_image']) : ?>
            <div class="price-review">
                <?php echo $this->getPriceHtml($_item, true) ?>
            <?php endif; ?>
            
            <div class="reviews-wrap">
                <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
            </div>
            <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
            <div class="actions clearfix">
                <?php if($_item->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php else: ?>
                    <span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
                <?php endif; ?>
                <span class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" class="button link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                        <a href="<?php echo $_compareUrl ?>" class="button link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                    <?php endif; ?>
                </span>
            </div>
            
            <?php if (!$b['product']['price_on_image']) : ?></div><?php endif; ?>
            
        </li>
    <?php endforeach; ?>
    </ul></div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
    <script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
        var bp = 963;
        if ($('body').hasClass('bv3'))
            bp = 975;
        $('#crosssell-products-list').flexslider({
            controlNav: false,
            animation: 'slide',
            animationLoop: false,
            minItems: 4,
            maxItems: 4,
            itemWidth: 228
        })
        .data("break_default", [4, 228])
        .data("break_points", [ [975, 3, 190], [750, 2, 190], [530, 1, 228] ] );
    });
    //]]>
    </script>
</div>
<?php endif; ?>
