<?php
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
<td class="no-border-right pr-img-td">
    <a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove2 for-mobile"><i class="icon-remove">&nbsp;</i></a>
    <?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image">
        <?php endif;?>
        <?php
        //Default image size
        $imgWidth = 180;
        $imgHeight = 180;

        //Aspect Ratio
        if ($b['product']['aspect_ratio'])
            $imgHeight = $imgWidth * $b['product']['image_ratio'];
        ?>
        <img src="<?php echo $zonda->getImage($this->getProduct(), $imgWidth, $imgHeight, 'thumbnail'); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
        <?php if ($this->hasProductUrl()):?></a><?php endif;?></td>
<td class="a-left product-name-td">
    <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?>
    </h2>
    <?php if ($_options = $this->getOptionList()):?>
        <div class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <div><?php echo $this->htmlEscape($_option['label']) ?>:&nbsp;<b><?php echo $_formatedOptionValue['value'] ?></b>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <div class="truncated_full_value">
                            <div class="item-options">
                                <div><?php echo $this->htmlEscape($_option['label']) ?>:&nbsp;<b><?php echo $_formatedOptionValue['full_view'] ?></b></div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif;?>
    <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>"><?php echo $this->escapeHtml($message['text']) ?></p>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php /* Start item added to cart custom content */ ?>

    <?php
/**

    $productid = $_item->getProductId();

    if($productid == "29" || $productid == "30"){
        echo '<p class="item-msg red">Due to high demand, the Microsphere Gel is temporarily on back order. Your entire order won\'t ship until the week of March 21. We apologize for this inconvenience.</p>';
    }

**/

    $productid = $_item->getProductId();

    if($productid == "46" || $productid == "45"){
        echo '<p class="item-msg red">Expected ship date: Monday, 5/2</p>';
    }

    ?>

    <?php /*End item added to cart custom content */ ?>

    <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock): ?>
        <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
    <?php endif;?>
</td>
<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td class="a-center">
        <?php if ($isVisibleProduct): ?>
            <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
        <?php endif ?>
    </td>
<?php endif ?>
<td class="a-center">
    <?php echo "<span class='for-mobile-inline'>".$this->__('Product Code : ')."</span>" ?>
    <?php echo $_item->getSku(); ?>
</td>
<?php if ($canApplyMsrp): ?>
    <td class="a-center unit-price"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
        <?php echo "<span class='for-mobile-inline'>".$this->__('Unit price : ')."</span>" ?>
        <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
            <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
    </td>
<?php else: ?>

    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-center unit-price">
            <?php echo "<span class='for-mobile-inline'>".$this->__('Unit price : ')."</span>" ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                    <?php else: ?>
                        <?php $_price = $_item->getProduct()->getPrice(); ?>
                        <?php $_finalPrice = $_item->getCalculationPrice(); ?>
                        <?php if ($_price > $_finalPrice): ?>
                            <p class="<?php if ($_finalPrice == 0.00){echo 'free-price ';} ?>old-price">
                                <?php echo $this->helper('checkout')->formatPrice($_item->getProduct()->getPrice()); ?>
                            </p>
                        <?php
                            $discountAmt = $_item->getDiscountAmount();
                            $discountedAmount = ($_item->getCalculationPrice() - ($_item->getDiscountAmount()/$_item->getQty()));
                            ?>
                        <?php if ($discountAmt > 0): ?>
                                <p class="special-price"><?php echo $this->helper('checkout')->formatPrice($discountedAmount) ?></p>
                            <?php else: ?>
                                <p class="special-price">
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                                </p>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php
                            $discountAmt = $_item->getDiscountAmount();
                            $discountedAmount = ($_item->getCalculationPrice() - ($_item->getDiscountAmount()/$_item->getQty()));
                            ?>
                            <?php if ($discountAmt > 0): ?>
                                <p class="old-price"><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?></p>
                                <p class="special-price"><?php echo $this->helper('checkout')->formatPrice($discountedAmount) ?></p>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>

            </span>


                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-center unit-price">
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
            <?php endif; ?>

            </span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>
<?php endif; ?>
<td class="a-center qty-td">
    <div class="qty-holder">
        <input type="text" name="cart[<?php echo $_item->getId() ?>][qty]" maxlength="12" value="<?php echo $this->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <a href="javascript:void(0)" class="button button-up for-mobile"><span>+</span></a>
        <div class="clear"></div>
    </div>
</td>
<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="a-center sub-total">
        <?php echo "<span class='for-mobile-inline'>".$this->__('Subtotal : ')."</span>" ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                    <?php else: ?>
                        <?php if ($discountAmt > 0): ?>
                            <?php
                            $subtotalAmt = $_item->getRowTotal();
                            $discountedSubtotal = $subtotalAmt - $discountAmt;
                            ?>
                            <?php echo $this->helper('checkout')->formatPrice($discountedSubtotal) ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()); ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>

        </span>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
    </td>
<?php endif; ?>
<?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="a-center sub-total">
        <?php echo "<span class='for-mobile-inline'>".$this->__('Subtotal : ')."</span>" ?>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif; ?>
                <?php endif; ?>

        </span>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
    </td>
<?php endif; ?>
<td class="a-center rm-td for-desktop"><a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove"><i class="icon-remove">&nbsp;</i></a></td>
</tr>

<script type="text/javascript">
    if(typeof optimizely !== 'undefined') {
        /* _optimizely_evaluate=force */
        if(optimizely.variationNamesMap[5686090405].split(", ")[0] == "Original") {
            console.log('Original');
        }
        else if(optimizely.variationNamesMap[5686090405].split(", ")[0] == "novalue") {
            console.log('novalue');
            jQuery(".ampromo-price").hide();
            jQuery(".free-price").hide();
        } else {
            console.log('test with value');
        }
        /* _optimizely_evaluate=safe */
        //...OR...
        /* _optimizely_evaluate=safe */
    }
</script>