<?php
    $helper = Mage::helper('md_partialpayment');
    $payment = $this->getPayment();
    $store = Mage::app()->getStore($payment->getStoreId());
            $name = array(
                $store->getWebsite()->getName(),
                $store->getGroup()->getName(),
                $store->getName()
            );
    $order = $payment->getOrder();
    $orderItem = $payment->getOrderItem();
    $summaryCollection = $payment->getPaymentSummaryCollection();
    $ids = $summaryCollection->getAllIds();
    $summaryStatusMap = array(
        MD_Partialpayment_Model_Summary::PAYMENT_FAIL=>array("label"=>$helper->__('Failed'),"class"=>"grid-severity-critical"),
        MD_Partialpayment_Model_Summary::PAYMENT_PENDING=>array("label"=>$helper->__('Pending'),"class"=>"grid-severity-minor"),
        MD_Partialpayment_Model_Summary::PAYMENT_SUCCESS=>array("label"=>$helper->__('Paid'),"class"=>"grid-severity-notice"),
        MD_Partialpayment_Model_Summary::PAYMENT_HOLD=>array("label"=>$helper->__('Hold'),"class"=>"grid-severity-critical"),
        MD_Partialpayment_Model_Summary::PAYMENT_DECLINED=>array("label"=>$helper->__('Declined'),"class"=>"grid-severity-critical"),
        MD_Partialpayment_Model_Summary::PAYMENT_PROCESS=>array("label"=>$helper->__('Processing'),"class"=>"grid-severity-critical"),
    );
?>
<div class="content-header">
    <h3><?php echo $this->getTitle(); ?></h3>
    <div class="content-buttons-placeholder">
        <p class="content-buttons form-buttons">
            <button title="<?php echo $this->__('Back') ?>" type="button" class="scalable back" onclick="setLocation('<?php echo $this->getUrl('*/*/index') ?>')" style=""><span><span><span><?php echo $this->__('Back') ?></span></span></span></button>
        </p>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $helper->__('Payment Information') ?></h4>
    </div>
    <fieldset>
        <div class="box-left" style="width:100%;">
            <table border="0" width="100%">
                <tr>
                    <td width="45%">
                        <table class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label><?php echo $helper->__('Customer Name') ?></label></td>
                                    <td class="value">
                                        <?php if($this->getCustomerViewUrl()): ?>
                                        <a href="<?php echo $this->getCustomerViewUrl() ?>" target="_blank"><strong><?php echo $payment->getCustomerName() ?></strong></a>
                                        <?php else: ?>
                                        <strong><?php echo $payment->getCustomerName() ?></strong>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label><?php echo $helper->__('Customer Email') ?></label></td>
                                    <td class="value"><a href="mailto:<?php echo $payment->getCustomerEmail() ?>"><strong><?php echo $payment->getCustomerEmail() ?></strong></a></td>
                                </tr>
                                <tr>
                                   <td class="label"><label><?php echo $helper->__('Purchased From') ?></label></td>
                                    <td class="value"><strong><?php echo implode('<br/>', $name) ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td width="10%">&nbsp;</td>
                    <td width="45%">
                        <table class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label><?php echo $helper->__('Total Paid Amount') ?></label></td>
                                    <td class="value"><strong><?php echo $order->formatPrice($payment->getPaidAmount()) ?></strong></td>
                                </tr>
                                <tr>
                                    <td class="label"><label><?php echo $helper->__('Total Due Amount') ?></label></td>
                                    <td class="value"><strong><?php echo $order->formatPrice(max(0,$payment->getDueAmount())) ?></strong></td>
                                </tr>
                                <tr>
                                   <td class="label"><label><?php echo $helper->__('Paid Installments') ?></label></td>
                                    <td class="value"><strong><?php echo $payment->getPaidInstallments() ?></strong></td>
                                </tr>
                                <tr>
                                   <td class="label"><label><?php echo $helper->__('Due Installments') ?></label></td>
                                    <td class="value"><strong><?php echo max(0,$payment->getDueInstallments()) ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </table>
            
        </div>
    </fieldset>
</div>
<div class="entry-edit" style="width:100%;">
    <div class="entry-edit-head">
        <h4><?php echo $helper->__('Payment Installment Summary') ?></h4>
        <div class="form-buttons">
            <button style="margin-top:5px;" type="button" class="scalable " title="<?php echo $helper->__('Send Schedule Email') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/sendEmail',array('action'=>'schedule','payment_id'=>$payment->getId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Send Schedule Email') ?></span>
                                </span>
                            </span>
                        </button>
        </div>
    </div>
</div>
<form method="post" id="payment-summary-form" name="payment.summary.form" action="<?php echo Mage::helper('adminhtml')->getUrl('md_partialpayment/adminhtml_summary/pay') ?>">
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
    <div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables" style="width:100%;" id="my-summary-table">
            <colgroup>
                <col width="1"/>
                <col width="1"/>
                <col />
                <col />
                <col />
                <col />
                <col width="1"/>
                <col/>
            </colgroup>
            <thead>
                <tr class="headings">
                    <th>&nbsp;</th>
                    <th class="a-center"><?php echo $helper->__('Amount') ?></th>
                    <th class="a-center"><?php echo $helper->__('Due Date') ?></th>
                    <th class="a-center"><?php echo $helper->__('Paid Date') ?></th>
                    <th class="a-center"><?php echo $helper->__('Status') ?></th>
                    <th class="a-center"><?php echo $helper->__('Payment Method') ?></th>
                    <th class="a-center"><?php echo $helper->__('Details') ?></th>
                    <th class="a-center"><?php echo $helper->__('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($summaryCollection as $summary): ?>
                
                <?php $transactionDetails = ($summary->getTransactionData()) ? implode('<br />',$summary->getTransactionData()): '-'; ?>
                <tr>
                    <td class="a-center">
                       <?php $disabled = (in_array($summary->getStatus(),array(MD_Partialpayment_Model_Summary::PAYMENT_SUCCESS, MD_Partialpayment_Model_Summary::PAYMENT_PROCESS))) ? true: false; ?>
                       <input class="validate-one-required-by-name" type="radio" name="payment_summary" id="payment_summary_<?php echo $summary->getId() ?>" value="<?php echo $summary->getId() ?>" <?php if($disabled): ?>disabled="disabled"<?php endif; ?>/>
                    </td>
                    <td class="a-center"><?php echo $order->formatPrice($summary->getAmount()) ?></td>
                    <td class="a-center">
                        <?php $date = ($summary->getDueDate()) ? date('M d, Y', strtotime($summary->getDueDate())): 'N / A'; ?>
                        <?php echo $date ?>
                    </td>
                    <td class="a-center">
                        <?php $date = ($summary->getPaidDate()) ? date('M d, Y', strtotime($summary->getPaidDate())): 'N / A'; ?>
                        <?php echo $date ?>
                    </td>
                    <td class="a-left">
                        <span class="<?php echo $summaryStatusMap[$summary->getStatus()]['class'] ?>">
                            <span><?php echo $summaryStatusMap[$summary->getStatus()]['label'] ?></span>
                        </span>
                    </td>
                    <td class="a-left">
                        <?php echo Mage::getStoreConfig('payment/'.$summary->getPaymentMethod().'/title') ?>
                    </td>
                    <td class="a-center">
                        <?php if($transactionDetails !== '-'): ?>
                        <a href="javascript:void(0)" class="summary-details" id="link_<?php echo $summary->getId() ?>"><?php echo $helper->__('Details') ?></a>
                        <div id="trans_details_<?php echo $summary->getId() ?>" style="display:none;">
                            <div class="entry-edit">
                                <div class="entry-edit-head">
                                    <h4 class="icon-head fieldset-legend"><?php echo $helper->__('Payment Details') ?></h4>
                                </div>
                                <div class="content">
                                    <?php echo $transactionDetails; ?>
                                </div>
                            </div>
                        </div>
                        <?php else: ?>
                            <?php echo $transactionDetails; ?>
                        <?php endif; ?>
                    </td>
                    <td class="a-center">
                        <?php if($summary->getStatus() == MD_Partialpayment_Model_Summary::PAYMENT_PROCESS): ?>
                        <button type="button" class="scalable " title="<?php echo $helper->__('Confirm') ?>" onclick="confirmSetLocation('<?php echo $helper->__('Are you sure want to confirm this installment?') ?>','<?php echo $this->getUrl('*/*/confirmPayment',array('summary_id'=>$summary->getId(),'payment_id'=>$summary->getPaymentId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Confirm') ?></span>
                                </span>
                            </span>
                        </button>&nbsp;&nbsp;
                        <button style="margin-top:5px;" type="button" class="scalable " title="<?php echo $helper->__('Reject') ?>" onclick="confirmSetLocation('<?php echo $helper->__('Are you sure want to reject this installment?') ?>','<?php echo $this->getUrl('*/*/rejectPayment',array('summary_id'=>$summary->getId(),'payment_id'=>$summary->getPaymentId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Reject') ?></span>
                                </span>
                            </span>
                        </button>
                        <?php elseif($summary->getStatus() == MD_Partialpayment_Model_Summary::PAYMENT_SUCCESS): ?>
                        <button type="button" class="scalable " title="<?php echo $helper->__('Send Email') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/sendEmail',array('action'=>'success','summary_id'=>$summary->getId(),'payment_id'=>$summary->getPaymentId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Send Email') ?></span>
                                </span>
                            </span>
                        </button>
                        <?php elseif($summary->getStatus() == MD_Partialpayment_Model_Summary::PAYMENT_FAIL): ?>
                        <button type="button" class="scalable " title="<?php echo $helper->__('Send Email') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/sendEmail',array('action'=>'failed','summary_id'=>$summary->getId(),'payment_id'=>$summary->getPaymentId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Send Email') ?></span>
                                </span>
                            </span>
                        </button>
                        <?php elseif($summary->getStatus() == MD_Partialpayment_Model_Summary::PAYMENT_PENDING): ?>
                        <button type="button" class="scalable " title="<?php echo $helper->__('Send Reminder') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/sendEmail',array('action'=>'reminder','summary_id'=>$summary->getId(),'payment_id'=>$summary->getPaymentId())) ?>')">
                            <span>
                                <span>
                                    <span><?php echo $helper->__('Send Reminder') ?></span>
                                </span>
                            </span>
                        </button>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div><br />
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        var idsJson = '<?php echo Mage::helper('core')->jsonEncode($ids) ?>'.evalJSON(true);
        
        $$(".summary-details").each(function(summaryElement){
            Event.observe($(summaryElement),'click',function(event){
                var sourceElement = event.element();
                var sourceElementId = $(sourceElement).id;
                var splitedId = sourceElementId.split('_');
               
                if($('trans_details_'+splitedId[1]).getStyle('display') == 'none'){
                    $('trans_details_'+splitedId[1]).setStyle({display:'block',position:'absolute',zIndex:'100',background:'#FFFFFF',textAlign:'left'});
                }else{
                    $('trans_details_'+splitedId[1]).setStyle({display:'none'});
                }
                for(var idx=0;idx<idsJson.length;idx++){
                    if(splitedId[1] !== idsJson[idx]){
                        if($('trans_details_'+idsJson[idx])){
                            $('trans_details_'+idsJson[idx]).setStyle({display:'none'});
                        }
                    }
                    
                }
            });
        });
    });
</script>
<?php if($payment->canAllowToDoPayments()): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $helper->__('Payment Methods') ?></h4>
        <div class="form-buttons">
            <button disabled="disabled" type="submit" class="scalable disabled" title="<?php echo $helper->__('Make Payment') ?>"><span><span><span><?php echo $helper->__('Make Payment') ?></span></span></span></button>
        </div>
    </div>
    <fieldset>
        <div class="hor-scroll">
            <?php echo $this->getLayout()->createBlock('md_partialpayment/summary_payment_methods')->toHtml() ?>
            <script type="text/javascript">
                var partialPaymentForm = new varienForm('payment-summary-form');
                $$('.partial-payment-methods')[0].select('input[type="radio"]').each(function(element){
                if(element.name == "partial[method]"){
				Event.observe($(element),'change',function(event){
                    var tElement = event.element();
                    if(tElement.name != "<?php echo Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE ?>[<?php echo Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE ?>_payment_id]"){
                        $$('.partial-payment-methods')[0].select('input[type="radio"]').each(function(tmpElement){
                            if(tmpElement.name == "partial[method]"){
								if(tmpElement.value == tElement.value){
									$('payment_form_'+tmpElement.value).setStyle({display:"block"});
									$('payment-summary-form').select('button[type="submit"]')[0].disabled=false;
									$('payment-summary-form').select('button[type="submit"]')[0].removeClassName('disabled');
									$('payment_form_'+tmpElement.value).select('input[type="text"]','select').each(function(listElement){
										listElement.disabled=false;
									});
								}else{
									$('payment_form_'+tmpElement.value).setStyle({display:"none"});
									$('payment_form_'+tmpElement.value).select('input[type="text"]','select').each(function(listElement){
										listElement.disabled=true;
									});
								}
							}
                        });
                    }
                });
				}
           });
            </script>
        </div>
    </fieldset>
</div>
<?php endif; ?>
</form>