<script type="text/javascript">
//<![CDATA[
OptionTemplateText = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
            '<th class="type-sku"><?php echo Mage::helper('catalog')->__('Validation') ?></th>'+
			 '<th class="type-sku"><?php echo Mage::helper('catalog')->__('Max Char') ?></th>'+
        '</tr>'+
        '<tr>'+
            '<td><input type="text" class="input-text" name="easycontectvalues[{{option_id}}][validation]" value="{{validation}}" id="product_option_{{id}}_validation" /></td>'+
            '<td class="type-last last"><input type="text" class="input-text validate-zero-or-greater" name="easycontectvalues[{{option_id}}][max_characters]" value="{{max_characters}}"></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_text')) {
    $('option_panel_type_text').remove();
}
//]]>
</script>
