 
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

<?php foreach ($posts as $post): ?>
    <div class="postWrapper clearfix">
        <div class="postTitle heading">
            <?php echo $post->getTitle(); ?>
        </div>
        <div class="content clearfix">
            <div class="postDetails clearfix">
                <div class="postDate for-desktop detail-item left">
                    <span class="icon-calendar"></span></span><span><?php echo date('d M Y', strtotime($post->getCreatedTime())); ?></span>
                </div>
                <div class="postBy detail-item left">
                    <span class="icon-user"></span>
                    <span>By <?php echo $post->getUser(); ?></span>
                </div>                
                <?php if ($this->getCommentsEnabled()): ?>
                <div class="postComments detail-item left">
                    <span class="icon-comments"></span>
                    <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?>&nbsp;<?php echo $this->__('Comments'); ?></a>
                </div>
                <?php endif; ?>
                <div class="perm-link detail-item left">
                    <span class="icon-perm"></span>
                    <a href="<?php echo $post->getAddress(); ?>" ><span><?php echo $this->__('Permalink')?></span></a>
                </div>
                
            </div>
            <?php
                if($banner_content = $post->getBannerContent()){
            ?>
            <div class="postBanner">
                <?php echo $banner_content; ?>
            </div>
            <?php
                }
            ?>
            <div class="postContent">
               <?php echo $post->getPostContent(); ?>
            </div>
        </div>
    </div>
<?php endforeach; ?> 
<?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
<?php //echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
<?php //$this->getPages(); ?>
