<?php if ($posts = $this->getRecent()): ?>
<ul id="block-blog-bx" class="block-blog-slider bx-slider">
    <?php foreach ($posts as $post): ?>
    <li>
        <div class="heading"><?php echo $post->getTitle(); ?></div>
        <div class="block-from-blog-container">
            <div class="block-from-blog-photo">
                <?php
                    if($post_image = $post->getImage()){
                ?>
                <a href="<?php echo $post->getAddress(); ?>" >
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post_image; ?>" alt=""/>
                </a>
                <?php } ?>
            </div>
            <div class="block-from-blog-desc">
                <?php if(strlen($post->getShortContent()) > 130) echo substr($post->getShortContent(),0,130).'...'; else echo $post->getShortContent(); ?>
            </div>
            <a class="block-content-link" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read more')?></a>
        </div>
    </li>    
    <?php endforeach; ?> 
</ul>
<?php 
$counts = $this->getColumnCount(); 
if (!$counts)
    $counts = 3;
?>
<script type="text/javascript">// <![CDATA[
var blog_timer;    
var blog_slider;
var winwidth = jQuery(window).outerWidth();
if (winwidth < 992 && winwidth >= 768){
    blog_slider = jQuery('#block-blog-bx').bxSlider({minSlides: 2, maxSlides: 2, slideWidth:310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
}else if(winwidth < 768){
    blog_slider  = jQuery('#block-blog-bx').bxSlider({minSlides: 1, maxSlides: 1, slideWidth:310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
}else {
    blog_slider = jQuery('#block-blog-bx').bxSlider({minSlides: <?php echo $counts ?>, maxSlides: <?php echo $counts ?>, slideWidth:310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
}
jQuery(window).resize(function(e){
    e.preventDefault();
    winwidth = jQuery(window).outerWidth();
    if(blog_timer) clearTimeout(blog_timer);
    blog_timer = setTimeout(function(){
        if (winwidth < 992 && winwidth >= 768){
            blog_slider.reloadSlider({minSlides: 2, maxSlides: 2, slideWidth: 310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
        }else if(winwidth < 768){
            blog_slider.reloadSlider({minSlides: 1, maxSlides: 1, slideWidth: 310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
        }else {
            blog_slider.reloadSlider({minSlides: <?php echo $counts ?>, maxSlides: <?php echo $counts ?>, slideWidth: 310, slideMargin: 35, moveSlides: 1, nextText: "<i class='icon-brand-arrow'>&nbsp;</i>", prevText: "<i class='icon-brand-arrow'>&nbsp;</i>", pager: false });
        }}, 300
    );
});
// ]]></script>
<?php else: ?>
<div>
    <?php echo $this->__('There are no blogs') ?>
</div>
<?php endif; ?>
