<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper post clearfix">
    <div class="postTitle heading">
        <?php echo $post->getTitle(); ?>
    </div>
    <div class="content clearfix">
        <div class="postDetails clearfix">
            <div class="postDate for-desktop detail-item left">
                <span class="icon-calendar"></span></span><span><?php echo date('d M Y', strtotime($post->getCreatedTime())); ?></span>
            </div>
            <div class="postBy detail-item left">
                <span class="icon-user"></span>
                <span>By <?php echo $post->getUser(); ?></span>
            </div>                
            <?php if ($this->getCommentsEnabled()): ?>
            <div class="postComments detail-item left">
                <span class="icon-comments"></span>
                <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?>&nbsp;<?php echo $this->__('Comments'); ?></a>
            </div>
            <?php endif; ?>
            <div class="perm-link detail-item left">
                <span class="icon-perm"></span>
                <a href="<?php echo $post->getAddress(); ?>" ><span><?php echo $this->__('Permalink')?></span></a>
            </div>            
        </div>
        <?php
            if($banner_content = $post->getBannerContent()){
        ?>
        <div class="postBanner">
            <?php echo $banner_content; ?>
        </div>
        <?php
            }
        ?>
        <div class="postContent">
           <?php echo $post->getPostContent(); ?>           
        </div>
        <?php echo $this->getBookmarkHtml($post) ?>
    </div>        
    
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="postTitle heading"><a name="commentBox" ></a>
        <?php echo $this->__('Comments') ?> (<?php echo count($comments); ?>)
    </div>
    <?php $numItems = count($comments); ?>
    <div class="content comment-content">
        <?php if ($numItems): ?>
        <?php foreach ($comments as $comment) : ?>
            <?php if(++$i === $numItems) {
                $last = "end";
              } ?>
            <div class="commentWrapper <?php echo $last ?>">
                <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>       
        <?php endforeach; ?>    
        <?php else: ?>
            <?php echo Mage::helper('blog')->__('There are no comments') ?>
        <?php endif; ?> 
     <div class="clear"></div>
     </div>
     <?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">  
                    <div class="heading"><?php echo Mage::helper('blog')->__('Leave a Comment') ?></div>
                    <div class="content clearfix">
                        <fieldset class="group-select">
                            <ul class="form-list">
                                <li>
                                    <div class="input-box smartwave-blog-comment-area">
                                        <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5" placeholder="<?php echo $this->__('Enter Your Comment') ?> *"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </li>
                            </ul>
                        </fieldset>
                        <div class="button-set">
                            <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                            <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                            <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                            <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Post Comment') ?></span></span></button>
                        </div>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>            

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" class="blog-login"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <div class="legend heading"><?php echo Mage::helper('blog')->__('Leave a Comment') ?></div>
                <div class="content clearfix">
                    <fieldset class="group-select">
                        <ul class="form-list">
                            <li>
                                <div class="input-box">
                                    <label><?php echo $this->__('Name *: '); ?></label>
                                    <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                </div>

                                <div class="input-box">
                                    <label><?php echo $this->__('Email *: '); ?></label>
                                    <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text"  />
                                </div>

                                <div class="clear"></div>

                                <div class="input-box smartwave-blog-comment-area">
                                    <label><?php echo $this->__('Your Comment *: '); ?></label>
                                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5" ><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                    <?php
                            if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                                ?><div class="recaptcha"><?php
                    require_once 'recaptcha/recaptchalib-smartwave.php';

                    // Get a key from http://recaptcha.net/api/getkey
                    $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                    $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                    $error = null;

                    echo recaptcha_get_html($publickey, $error);
                                ?></div><?php
                }
                            ?>  
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Post Comment') ?></span></span></button>
                    </div>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
