<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
$zonda = $this->helper('zonda');
$b = $zonda->getConfigGroup();
$c = $zonda->getConfigGroupDesign();
$input_width = (int)$c['header']['search_input_width'];
if ($input_width <= 0)
    $input_width = 160;
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-search clearfix">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" /><button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span class="name"><span><?php echo $this->__('Search') ?></span></span><span class="icon-search"></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search here...') ?>');
            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
jQuery(function($) {
    var form_mini_timer;
    var search_input_width = <?php echo $input_width ?>;        
    function zonda_resize_searchbox() {
        var $input = $('#search_mini_form .form-search .input-text');
        search_input_width = <?php echo $input_width ?>;
        var header_right_width = $('.header-right').width();
        var header_menu_width = $('.nav-container').width() + search_input_width + $('.form-search .button').width();
        if ($(window).width() >= 768){            
            $('.header-right').removeClass('search-active');
        }else{
            search_input_width = $(window).width() - $('.form-search .button').width() - 20;
        }
        if (header_right_width <= header_menu_width ){
            $('#search_mini_form .form-search .input-text').addClass('pos-abs');
        }else{
            $('#search_mini_form .form-search .input-text').removeClass('pos-abs');
        }                
        if (header_right_width <= header_menu_width || (header_right_width > header_menu_width && $('.header-menu-right').length) && $(window).width() > 991 || $(window).width() < 768) {            
            if (!$('.header-right').hasClass('search-active')){                
                    $('#search_mini_form .form-search .button .icon-close').addClass('icon-search');
                    $('#search_mini_form .form-search .button .icon-close').removeClass('icon-close');
                    $('#search_mini_form .form-search .input-text').stop().animate({
                        width: 0,
                        left: 2
                    }, 400, function() {
                        $(this).hide();                
                    });   
                $('#search_mini_form .form-search .input-text').attr('data-mobile', '1');
            }else{                       
                $('#search_mini_form .form-search .input-text').show().stop().animate({
                    width: search_input_width,
                    left: -search_input_width
                }, 400);
            }
        } else {            
            $('#search_mini_form .form-search .input-text').show().stop().animate({
                width: search_input_width,
                left: -search_input_width
            }, 400);
            $('#search_mini_form .form-search .button .icon-close').addClass('icon-search');
            $('#search_mini_form .form-search .button .icon-close').removeClass('icon-close');                        
            $('#search_mini_form .form-search .input-text').attr('data-mobile', '');
        }
        if (form_mini_timer) clearTimeout(form_mini_timer); 
    }
    
    $(window).load(zonda_resize_searchbox);
    $(window).resize(function() {
        clearTimeout(form_mini_timer);         
        form_mini_timer = setTimeout(zonda_resize_searchbox, 200); 
    });
    $('#search_mini_form .button').click(function() {        
        var $input = $('#search_mini_form .form-search .input-text');
         if ( $(window).width() < 768 ){
            if (!$('.header-right').hasClass('search-active')){
                $('.header-right').addClass('search-active');
            }            
        }       
        if ($input.css('display') == 'none') {
            if ($('.header-menu-right').length || $(window).width() < 768){
                $('#search_mini_form .form-search .button .icon-search').addClass('icon-close');
                $('#search_mini_form .form-search .button .icon-search').removeClass('icon-search');
            }
            $input.show().stop().animate({
                width: search_input_width,
                left: -search_input_width
            }, 400);            
            return false;
        }
        var data_mobile = $('#search_mini_form .form-search .input-text').attr('data-mobile');
        var right_menu = false;
        var header_right_width = $('.header-right').width();
        var header_menu_width = $('.nav-container').width() + search_input_width + $('.form-search .button').width();
        if (header_menu_width > header_right_width && $('.header-menu-right').length)
            right_menu = true;
        var value = $('#search_mini_form .form-search .input-text').val();
        if ((data_mobile == '1' || right_menu) && value == '<?php echo $this->__('Search here...') ?>') {
            if ($input.css('display') == 'none') {                
            if ($('.header-menu-right').length || $(window).width() < 768){
                $('#search_mini_form .form-search .button .icon-search').addClass('icon-close');
                $('#search_mini_form .form-search .button .icon-search').removeClass('icon-search');
            }
                $input.show().stop().animate({
                    width: search_input_width,
                    left: -search_input_width
                }, 400);
            } else {
                $input.stop().animate({
                    width: 0,
                    left: 2
                }, 400, function() {
                    if ($('.header-menu-right').length || $(window).width() < 768){
                        $('#search_mini_form .form-search .button .icon-close').addClass('icon-search');
                        $('#search_mini_form .form-search .button .icon-close').removeClass('icon-close');
                    }
                    $(this).hide(); 
                    if ($('.header-right').hasClass('search-active')){
                        $('.header-right').removeClass('search-active');
                    }                   
                });
            }
            return false;
        }
    });
})
//]]>
</script>
