<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>
<div class="btn-affirm-wrapper">
    <a class="btn-affirm" href="<?php echo Mage::getUrl('checkout/onepage'); ?>">
        <img src="<?php echo $this->getSkinUrl('images/logo-affirm.png'); ?>" alt="Affirm Logo" class="logo-affirm"> Financing
    </a>
    <p class="affirm-orders">Available on orders of $149 or more.</p>
    <p class="affirm-select">Select <strong>Affirm</strong> when entering Payment Information.</p>
</div>