<div id="checkout-review" class="onepagecheckout_block">
    <div class="op_block_title heading"><?php echo $this->__('Review Your Order') ?></div>
	<div class="content">
		<div id="checkout-review-load">
			<?php echo $this->getChildHtml('info') ?>
		</div>		
	</div>
	<div id="checkout-review-submit">    
		<?php echo $this->getChildHtml('agreements') ?>
		<div class="buttons-set" id="review-buttons-container">
		<button type="submit" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout" onclick="checkout.save(); return false;"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
			<span class="please-wait" id="review-please-wait" style="display:none;">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
			</span>
		</div>
	</div>
</div>
