<?php
    $zonda = Mage::helper('zonda');
    $b = $zonda->getConfigGroup();
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $imgWidth  = 310;	
    $imgHeight  = 310;	
    if ($b['product']['aspect_ratio'])
        $imgHeight = $imgWidth * $b['product']['image_ratio'];
?>
<div id="product_img_slider">
<p class="product-image">
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600); ?>" class ='cloud-zoom' rel="position:'<?php echo $zoomPosition?>' ,tint: '<?php echo $zoomColor ?>',tintOpacity:0.5 ,smoothMove:5,zoomWidth:<?php echo $zoomWidth?>,zoomHeight:<?php echo $zoomHeight?>,adjustY:-40, adjustX:100, zoomFlyOut:false,zoomSizeMode:'lens' ">	
<?php
	$_img = '<img id="image" width="'.$imgWidth.'" height="'.$imgHeight.'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgWidth,$imgHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
	echo $_helper->productAttribute($_product, $_img, 'image');
?>
	</a>
</p>
</div>