<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="order-products-table" id="checkout-review-table">
        <col />
        <col width="1" />
        <thead>
            <tr class="for-desktop">
                <th><?php echo $this->__('Product') ?></th>
                <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <tr class="for-mobile">
                <th colspan="2"><?php echo $this->__('Product') ?></th>
            </tr>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
