<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    $zonda = $this->helper('zonda');
    $b = $zonda->getConfigGroup();
    
if ($b['category']['banner_position'] == 'bottom') : ?>
    <div class="category-banner">
        <?php if($_imgUrl): ?>
            <?php echo $_imgHtml ?>
        <?php else: ?>
            <div class="page-title category-title">
                <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
                    <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
                <?php endif; ?>
                <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php if($this->isContentMode()): ?>
    <?php  echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
