<?php
    $helper = Mage::helper('md_partialpayment');
    $paymentConfig = Mage::getSingleton('payment/config');
    $methods = $this->getActiveMethods();
    $oneMethod = count($methods) <= 1;
    $ccTypes = $paymentConfig->getCcTypes();
    $months = $paymentConfig->getMonths();
    $years = $paymentConfig->getYears();
    
    $_ccRequiredMethod = array(
    Mage_Paygate_Model_Authorizenet::METHOD_CODE,
     'authorizenet_directpost',
     'ccsave'
    );
    
    $_ccRedirectMethod = array(
        Mage_Paypal_Model_Config::METHOD_WPS
    );
    
    $_adminRequiredActionMethod = array(
        'cashondelivery',
        'checkmo'
    );
    $checkPaybleto = Mage::getStoreConfig('payment/checkmo/payable_to');
    $checkMailingAddress = Mage::getStoreConfig('payment/checkmo/mailing_address');
    
    $cashOnDeliveryInstructions = Mage::getStoreConfig('payment/cashondelivery/instructions');
?>
<style type="text/css">
    .partial-payment-methods dt label{
        color:#636363;
        background-color: #f4f4f4;
        display: inline-block;
        width: auto;
        max-width: none;
        min-width: 285px;
        float: none;
        padding: 6px 10px 6px 40px;
    }
    .partial-payment-methods dt input.radio{
        float: left;
        margin-right: -40px;
        margin-top: 10px;
        margin-left: 15px;
        position:relative;
    }
    .partial-payment-methods dt{
        margin: 0 0 5px;
    }
    .partial-payment-methods select.year{
        width: 96px !important;
    }
    .partial-payment-methods select.month{
        width: 120px !important;
        margin-right: 10px !important;
    }
    .partial-payment-methods p.required{
        margin-bottom: 5px;
        float: right;
        font-size: 12px;
        margin-top: 0px;
        color:red;
    }
</style>
<?php if (empty($methods)): ?>
<dl>
   <dt>
        <?php echo $this->__('No Payment Methods') ?>
    </dt> 
</dl>
    
<?php else:?> <dl class="partial-payment-methods"> <?php
    
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>

    <dt>
        <input id="partial_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="partial[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio validate-one-required-by-name" />
        <label for="partial_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($_method->getTitle()) ?></label>
    </dt>   
    <?php if($_method->getCode() && in_array($_code,$_ccRequiredMethod)): ?>
    <dd>
        <table class="form-list" id="payment_form_<?php echo $_code ?>" cellpadding="0" cellspacing="0" style="display:none;">
            <?php if($_method->getCode() == 'ccsave'): ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label></td>
                <td class="value"><input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="<?php echo $_code ?>[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" /></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_type" class="required">
                <em>*</em>
                    <?php echo $this->__('Credit Card Type') ?>
                </label></td>
                <td class="value">
                    <select id="<?php echo $_code ?>_cc_type" name="<?php echo $_code ?>[cc_type]" class="select required-entry validate-cc-type-select" title="<?php echo $this->__('Credit Card Type') ?>" autocomplete="off">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php foreach($ccTypes as $code=>$label): ?>
                            <option value="<?php echo $code ?>"><?php echo $label ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label></td>
                <td class="value"><input type="text" id="<?php echo $_code ?>_cc_number" name="<?php echo $_code ?>[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" /></td>
            </tr>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label></td>
                <td class="value">
                    <select id="<?php echo $_code ?>_expiration" name="<?php echo $_code ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
                
                <?php foreach ($months as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                    <select id="<?php echo $_code ?>_expiration_yr" name="<?php echo $_code ?>[cc_exp_year]" class="year required-entry">
                <?php foreach ($years as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </td>
            </tr>
            <?php if($_method->hasVerification()): ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label></td>
                <td class="value"><input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="<?php echo $_code ?>[cc_cid]" value="" /></td>
            </tr>
            <?php endif; ?>
        </table>
    </dd>
    <?php elseif($_method->getCode() && (in_array($_method->getCode(),$_ccRedirectMethod) || in_array($_method->getCode(),$_adminRequiredActionMethod))): ?>
    <dd>
        <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
            <?php if($_method->getCode() == Mage_Paypal_Model_Config::METHOD_WPS): ?>
            <li class="form-alt"><?php echo $this->__('You will be redirected to the PayPal website when you place an order.'); ?></li>
            <?php elseif($_method->getCode() == 'cashondelivery' && $cashOnDeliveryInstructions): ?>
            <li>
                <div class="cashondelivery-instructions-content">
                    <?php echo nl2br($cashOnDeliveryInstructions) ?>
                </div>
            </li>
            <?php elseif($_method->getCode() == 'checkmo'): ?>
            <?php if($checkPaybleto): ?>
            <li><label><?php echo $this->__('Make Check payable to: ') ?></label><?php echo $checkPaybleto ?></li>
            <?php endif; ?>
            <?php if($checkMailingAddress): ?>
            <li><label><?php echo $this->__('Send Check to: ') ?></label><address class="checkmo-mailing-address"><?php echo nl2br($checkPaybleto) ?></address></li>
            <?php endif; ?>
            <?php endif; ?>
        </ul>
    </dd>
    <?php endif; ?>
<?php endforeach;?>
</dl>    
<?php
endif; ?>