<?php
    $helper = Mage::helper('md_partialpayment');
    $paymentConfig = Mage::getSingleton('payment/config');
    $paymentId = $this->getRequest()->getParam('id',null);
    $payments = Mage::getModel('md_partialpayment/payments')->load($paymentId);
    $methods = $this->getActiveMethods();
    $oneMethod = count($methods) <= 1;
    $ccTypes = $paymentConfig->getCcTypes();
    $months = $paymentConfig->getMonths();
    $years = $paymentConfig->getYears();
    
    $_ccRequiredMethod = array(
    Mage_Paygate_Model_Authorizenet::METHOD_CODE,
     'authorizenet_directpost',
     'ccsave',
     Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE,
    );
    
    $_ccRedirectMethod = array(
        Mage_Paypal_Model_Config::METHOD_WPS
    );
    
    $_adminRequiredActionMethod = array(
        'cashondelivery',
        'checkmo'
    );
    $checkPaybleto = Mage::getStoreConfig('payment/checkmo/payable_to');
    $checkMailingAddress = Mage::getStoreConfig('payment/checkmo/mailing_address');
    
    $cashOnDeliveryInstructions = Mage::getStoreConfig('payment/cashondelivery/instructions');
?>
<style type="text/css">
    .partial-payment-methods dt label{
        color:#636363;
        background-color: #f4f4f4;
        display: inline-block;
        width: auto;
        max-width: none;
        min-width: 285px;
        float: none;
        padding: 6px 10px 6px 40px;
    }
    .partial-payment-methods dt input.radio{
        float: left;
        margin-right: -40px;
        margin-top: 10px;
        margin-left: 15px;
        position:relative;
    }
    .partial-payment-methods dt{
        margin: 0 0 5px;
    }
    .partial-payment-methods select.year{
        width: 96px !important;
    }
    .partial-payment-methods select.month{
        width: 120px !important;
        margin-right: 10px !important;
    }
    .partial-payment-methods p.required{
        margin-bottom: 5px;
        float: right;
        font-size: 12px;
        margin-top: 0px;
        color:red;
    }
</style>
<?php if (empty($methods)): ?>
<dl>
   <dt>
        <?php echo $this->__('No Payment Methods') ?>
    </dt> 
</dl>
    
<?php else:?> <dl class="partial-payment-methods"> <?php
    
    foreach ($methods as $_method):
        $_code = $_method->getCode();
    $cards = $helper->getCardsByMethods($_code,$payments->getStoreId());
?>

    <dt>
        <input id="partial_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="partial[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio validate-one-required-by-name" />
        <label for="partial_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($_method->getTitle()) ?></label>
    </dt>   
    <?php if($_method->getCode() && in_array($_code,$_ccRequiredMethod)): ?>
    <dd>
        <table class="form-list" id="payment_form_<?php echo $_code ?>" cellpadding="0" cellspacing="0" style="display:none;">
            <?php if($_method->getCode() == 'ccsave'): ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label></td>
                <td class="value"><input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="<?php echo $_code ?>[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" /></td>
            </tr>
            <?php elseif($_method->getCode() == Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE): ?>
            <tr>
                <td colspan="2">
                    <table id="<?php echo $_code ?>_cc_saved_cards" class="fields">
                        <?php foreach ($helper->getAuthorizeNetCimSavedCard(Mage::getModel('customer/customer')->load($payments->getCustomerId()),$payments) as $stored_card) : ?>
                        <?php
                            $cc_num = $stored_card->getCcNumber();
                            $lastFourList[] = substr($stored_card->getCcNumber(),-4);
                        ?>
                        <tr>
                            <td class="label">
                                
                             </td>
                             <td class="value">
                                 <input type="radio" name="<?php echo $_code ?>[authorizenetcim_payment_id]" value="<?php echo $stored_card->getGatewayId(); ?>" id="cc_saved_<?php echo $stored_card->getGatewayId(); ?>" class="radio" />
                                 <label for="cc_saved_<?php echo $stored_card->getGatewayId(); ?>"><?php echo $this->__('Card Ending in: ') . $stored_card->getCcNumber(); ?></label> 
                             </td>
                        </tr>
                        <?php endforeach; ?>
                        <tr>
                            <td class="label">
                                
                            </td> 
                            <td class="value">
                                <input type="radio" name="<?php echo $_code ?>[authorizenetcim_payment_id]" value="" id="cc_enter_new_card" checked="checked" class="radio" />
                                <label for="cc_enter_new_card"><?php echo $this->__('Enter a New Credit Card') ?></label>
                            </td> 
                        </tr>
                    </table>
                    <table id="<?php echo $_code ?>_cc_new_card_form">
                        <tr>
                            <td class="label"><label for="<?php echo $_code ?>_cc_type" class="required">
                                <em>*</em>
                                    <?php echo $this->__('Credit Card Type') ?>
                                </label></td>
                            <td class="value">
                                <select id="<?php echo $_code ?>_cc_type" name="<?php echo $_code ?>[cc_type]" class="select required-entry validate-cc-type-select" title="<?php echo $this->__('Credit Card Type') ?>" autocomplete="off">
                                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                                        <?php foreach($ccTypes as $code=>$label): ?>
                                            <?php if(in_array($code,$cards)): ?>
                                            <option value="<?php echo $code ?>"><?php echo $label ?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label></td>
                            <td class="value"><input type="text" id="<?php echo $_code ?>_cc_number" name="<?php echo $_code ?>[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" /></td>
                        </tr>
                        <tr>
                            <td class="label"><label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label></td>
                            <td class="value">
                                <select id="<?php echo $_code ?>_expiration" name="<?php echo $_code ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
                                    <?php foreach ($months as $k=>$v): ?>
                                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                                    <?php endforeach ?>
                                </select>
                                <select id="<?php echo $_code ?>_expiration_yr" name="<?php echo $_code ?>[cc_exp_year]" class="year required-entry">
                                    <?php foreach ($years as $k=>$v): ?>
                                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                                    <?php endforeach ?>
                                </select>
                            </td>
                        </tr>
                        <?php if($_method->hasVerification()): ?>
                        <tr>
                            <td class="label"><label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label></td>
                            <td class="value"><input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="<?php echo $_code ?>[cc_cid]" value="" /></td>
                        </tr>
                        <?php endif; ?>
                        <?php if($_method->getCode() == Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE): ?>
                        <tr id="<?php echo $_code ?>_save_card_wrapper">
                            <td class="label">
                                <div class="input-box">
					<input type="checkbox" title="<?php echo $this->__('Save Card for Future Use') ?>" class="input-text" id="<?php echo $_code ?>_save_card" name="<?php echo $_code ?>[cc_save_card]" value="Yes" style="width: 15px;" /><?php echo $this->__('Save this card for future use') ?>            
				</div>
                            </td>
                            <td class="value"><label for="<?php echo $_code ?>_save_card"></label></td>
                        </tr>
                        <?php endif; ?>
                    </table>
                </td>
            </tr>    
            <?php endif; ?>
            <?php if($_method->getCode() != Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE): ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_type" class="required">
                <em>*</em>
                    <?php echo $this->__('Credit Card Type') ?>
                </label></td>
                <td class="value">
                    <select id="<?php echo $_code ?>_cc_type" name="<?php echo $_code ?>[cc_type]" class="select required-entry validate-cc-type-select" title="<?php echo $this->__('Credit Card Type') ?>" autocomplete="off">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php foreach($ccTypes as $code=>$label): ?>
                            <?php if(in_array($code,$cards)): ?>
                            <option value="<?php echo $code ?>"><?php echo $label ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label></td>
                <td class="value"><input type="text" id="<?php echo $_code ?>_cc_number" name="<?php echo $_code ?>[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" /></td>
            </tr>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label></td>
                <td class="value">
                    <select id="<?php echo $_code ?>_expiration" name="<?php echo $_code ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
                
                <?php foreach ($months as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                    <select id="<?php echo $_code ?>_expiration_yr" name="<?php echo $_code ?>[cc_exp_year]" class="year required-entry">
                <?php foreach ($years as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </td>
            </tr>
            <?php if($_method->hasVerification()): ?>
            <tr>
                <td class="label"><label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label></td>
                <td class="value"><input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="<?php echo $_code ?>[cc_cid]" value="" /></td>
            </tr>
            <?php endif; ?>
            <?php endif; ?>
        </table>
    </dd>
    <?php elseif($_method->getCode() && (in_array($_method->getCode(),$_ccRedirectMethod) || in_array($_method->getCode(),$_adminRequiredActionMethod))): ?>
    <dd>
        <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
            <?php if($_method->getCode() == Mage_Paypal_Model_Config::METHOD_WPS): ?>
            <li class="form-alt"><?php echo $this->__('You will be redirected to the PayPal website when you place an order.'); ?></li>
            <?php elseif($_method->getCode() == 'cashondelivery' && $cashOnDeliveryInstructions): ?>
            <li>
                <div class="cashondelivery-instructions-content">
                    <?php echo nl2br($cashOnDeliveryInstructions) ?>
                </div>
            </li>
            <?php elseif($_method->getCode() == 'checkmo'): ?>
            <?php if($checkPaybleto): ?>
            <li><label><?php echo $this->__('Make Check payable to: ') ?></label><?php echo $checkPaybleto ?></li>
            <?php endif; ?>
            <?php if($checkMailingAddress): ?>
            <li><label><?php echo $this->__('Send Check to: ') ?></label><address class="checkmo-mailing-address"><?php echo nl2br($checkPaybleto) ?></address></li>
            <?php endif; ?>
            <?php endif; ?>
        </ul>
    </dd>
    <?php endif; ?>
    <?php if($_method->getCode() == Gorilla_AuthorizenetCim_Model_Gateway::METHOD_CODE): ?>
    <script type="text/javascript">
	$$('#<?php echo $_code ?>_cc_saved_cards input').each(function(element){
		Event.observe(element, 'click', function(event){
			var cimNewCardForm = $("<?php echo $_code ?>_cc_new_card_form");
			if(element.value.length == 0){
				cimNewCardForm.show();
				cimNewCardForm.select('input','select','textarea').each(function(elm){
					elm.disabled = false;
				});
			} else {
				cimNewCardForm.hide();
				$("<?php echo $_code ?>_cc_new_card_form").select('input','select','textarea').each(function(elm){
					elm.disabled = true;
				});
			}
		});
	});
        
        Array.prototype.contains = function(obj) {
            var i = this.length;
            while (i--) {
                if (this[i] === obj) {
                    return true;
                }
            }
            return false;
        }
         
        // Add a Rule for Validating against duplicates
        Validation.addAllThese([
        ['validate-cc-duplicate', 'The customer already has this card on file, please select this existing card or enter a new one.', function(v, elm) {
                    <?php if (!empty($lastFourList)) : ?>
                        var lastFours = ["<?php echo implode('","', $lastFourList); ?>"];
                        var currentLastFour = v.slice(v.length-4,v.length); //get the last four chars of THIS cc
                        if (lastFours.contains(currentLastFour)) {
                            return false;
                        }
                    <?php endif; // Just return true if we don't have stored CCs ?>
                    return true;
                }] 
        ]);
</script>
    <?php endif; ?>
<?php endforeach;?>
</dl>    
<?php
endif; ?>