<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
$products = $this->getNewItems();
?>
<?php if (sizeof($products) > 0): ?>
    <script type="text/javascript">
        Object.extend(Product.Config.prototype, {
            reloadOptionLabels: function(){},
            changeSelection: function(){},
            reloadPrice: function(){}
        });
    </script>

    <div id="ampromo-overlay" style="display: none;">
        <div id="ampromo-items" class="<?php echo sizeof($products) > 3 ? 'amcarousel' : ''?>">
            <h3><?php echo $this->__('Select Your <span class="ampromo-freegift">Free Gift</span>')?></h3>

            <a href="javascript:" class="close"></a>

            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/view/options/js.phtml')->toHtml() ?>
            <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml() ?>

            <a href="javascript:" class="ampromo-carousel-control prev" rel="prev">Previous slide</a>
            <div id="ampromo-carousel-wrapper">
                <div id="ampromo-carousel-content">
                    <?php foreach ($products as $product): ?>
                        <div class="slide">
                            <div class="ampromo-item" data-product-id="<?php echo $product->getId()?>" data-product-sku="<?php echo $product->getSku()?>"<?php if($product->getTypeId() == 'amgiftcard'):?>style="width: 400px;"<?php endif;?>>
                                <form method="POST" action="<?php echo $this->getFormActionUrl()?>" class="ampromo_items_form" id="ampromo_items_form-<?php echo $product->getId()?>">
                                    <input type='hidden' name='referer' value='<?php echo $this->_getReferer()?>' />

                                    <img src="<?php echo $product->getSmallImageUrl(160, 160) ?>" class="ampromo-item-image"/>

                                    <div class="ampromo-item-title">
                                        <?php if ($product->getVisibility() != Mage_Catalog_Model_Product_Visibility::VISIBILITY_NOT_VISIBLE):?>
                                            <h4><a href="<?php echo $product->getProductUrl()?>"><?php echo $product->getName()?></a></h4>
                                        <?php else: ?>
                                            <h4><?php echo $product->getName()?></h4>
                                        <?php endif?>
                                    </div>

                                    <div class="ampromo-item-options"  <?php if($product->getTypeId() == 'amgiftcard'):?>style="overflow-y: scroll; max-height: 300px"<?php endif;?>>
										<?php
										switch($product->getTypeId()){
											case 'configurable';
												$_blockOpt = 'catalog/product_view_type_configurable';
												$_templateOpt = 'amasty/ampromo/items/configurable.phtml';
												break;
											case 'bundle':
												$_blockOpt = 'ampromo/items_bundle';
												$_templateOpt = 'bundle/catalog/product/view/type/bundle/options.phtml';
												break;
											case 'amgiftcard':
												$_blockOpt = 'amgiftcard/catalog_product_view_type_giftCard';
												$_templateOpt = 'amasty/amgiftcard/catalog/product/view/type/giftcard.phtml';
												break;
										}
										if(!empty($_blockOpt) && !empty($_templateOpt)) {
											echo $this->getLayout()
                                                ->createBlock(
                                                    $_blockOpt,
                                                    'ampromo_item_' . $product->getId(),
                                                    array('product' => $product)
                                                )
												->setProduct($product)
												->setTemplate($_templateOpt)
												->toHtml()
											;
										}
										?>

                                        <?php echo $this->getLayout()
                                            ->createBlock('ampromo/items_options', '', array('product' => $product))
                                            ->toHtml()
                                        ;?>
                                    </div>

                                    <input type="hidden" value="<?php echo $product->getId() ?>" name="product_id" />

                                    <div class="ampromo-price">
                                   (<?php
                                    $_product = Mage::getModel('catalog/product')->load($product->getId());
                                    echo Mage::helper('core')->formatPrice($_product->getPrice(), false);
                                    ?>
                                        Value)
                                    </div>

                                    <div class="ampromo-item-buttons">
                                        <button type="button" title="<?php echo $this->__('Add to cart')?>" class="button btn-cart add"><span><span><?php echo $this->__('Add Free Gift')?></span></span></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <a href="javascript:" class="ampromo-carousel-control next" rel="next">Next slide</a>
        </div>
    </div>

    <script type="text/javascript">
        if(typeof optimizely !== 'undefined') {
            /* _optimizely_evaluate=force */
            if (optimizely.variationNamesMap[5686090405].split(", ")[0] == "Original") {
                console.log('Original');
            }
            else if(optimizely.variationNamesMap[5686090405].split(", ")[0] == "novalue") {
                console.log('novalue');
                jQuery(".ampromo-price").hide();
            } else {
                console.log('test with value');
            }
            /* _optimizely_evaluate=safe */
            //...OR...
            /* _optimizely_evaluate=safe */
        }
    </script>

<?php endif ?>
